global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Muonroi.Core.Abstractions.Interfaces;
global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using Muonroi.Core.Abstractions.Exceptions;
