using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

namespace Muonroi.Pdf.SourceGenerators;

/// <summary>
/// Incremental source generator that discovers [PdfTemplate]-decorated model classes and emits:
/// 1. A sealed <c>{TypeName}PdfRenderer</c> implementing <c>IMPdfRenderer&lt;TModel&gt;</c> with
///    the HTML template inlined as a C# interpolated string (3x throughput vs. runtime resource load).
/// 2. A <c>{TypeName}PdfRendererServiceExtensions</c> static class with an
///    <c>AddPdfRenderer{TypeName}(IServiceCollection)</c> DI extension method.
/// </summary>
[Generator]
public sealed class PdfTemplateGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Muonroi.Pdf.Abstractions.PdfTemplateAttribute";

    /// <summary>
    /// Attribute source text emitted via RegisterPostInitializationOutput so the attribute
    /// resolves in consumer compilations that do not directly reference Muonroi.Pdf.Abstractions.
    /// </summary>
    private const string AttributeSourceText = @"// <auto-generated />
#nullable enable
using System;

namespace Muonroi.Pdf.Abstractions
{
    /// <summary>
    /// Marks a model class for compile-time IMPdfRenderer&lt;TModel&gt; generation.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
    public sealed class PdfTemplateAttribute : Attribute
    {
        /// <summary>Initializes a new instance of <see cref=""PdfTemplateAttribute""/>.</summary>
        /// <param name=""templateId"">Unique identifier for the PDF template.</param>
        /// <param name=""templateResourceName"">Optional embedded-resource name of the HTML template file.</param>
        public PdfTemplateAttribute(string templateId, string? templateResourceName = null)
        {
            TemplateId = templateId;
            TemplateResourceName = templateResourceName;
        }
        /// <summary>Gets the unique identifier for this PDF template.</summary>
        public string TemplateId { get; }
        /// <summary>Gets the optional embedded-resource name of the HTML template file.</summary>
        public string? TemplateResourceName { get; }
    }
}
";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Emit PdfTemplateAttribute into every consumer compilation.
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("PdfTemplateAttribute.g.cs", SourceText.From(AttributeSourceText, Encoding.UTF8)));

        // Step 2: Discover [PdfTemplate]-decorated classes/structs.
        IncrementalValuesProvider<PdfTemplateModel?> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, ct) => Transform(ctx, ct))
            .Where(static m => m is not null);

        // Step 3: Combine models with AdditionalTexts so template HTML can be inlined.
        IncrementalValueProvider<ImmutableArray<AdditionalText>> additionalTexts =
            context.AdditionalTextsProvider.Collect();

        IncrementalValuesProvider<(PdfTemplateModel Model, ImmutableArray<AdditionalText> Texts)> combined =
            models.Combine(additionalTexts)
                  .Select(static (pair, _) => (Model: pair.Left!, Texts: pair.Right));

        context.RegisterSourceOutput(combined, static (spc, pair) => EmitRenderer(spc, pair.Model, pair.Texts));
    }

    // -----------------------------------------------------------------------
    // Transform: extract model from [PdfTemplate]-decorated symbol
    // -----------------------------------------------------------------------

    private static PdfTemplateModel? Transform(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // Locate the [PdfTemplate] attribute data
        AttributeData? attrData = null;
        foreach (var attr in typeSymbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == AttributeFullName)
            {
                attrData = attr;
                break;
            }
        }

        if (attrData is null) return null;

        // Extract templateId (required, first constructor arg)
        string? templateId = null;
        if (attrData.ConstructorArguments.Length >= 1)
            templateId = attrData.ConstructorArguments[0].Value as string;

        if (string.IsNullOrEmpty(templateId))
        {
            // PDFSG0002 — report on the first syntax reference of the symbol
            var location = typeSymbol.Locations.FirstOrDefault() ?? Location.None;
            // Note: diagnostics emitted in transform are not surfaced; they must be emitted in source output.
            // We return a sentinel model with null TemplateId so EmitRenderer can emit the diagnostic.
            return new PdfTemplateModel(
                typeSymbol.ToDisplayString(),
                typeSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty,
                typeSymbol.Name,
                TemplateId: null,
                TemplateResourceName: null,
                IsPartial: IsPartial(ctx.TargetNode),
                Location: location);
        }

        string? templateResourceName = null;
        if (attrData.ConstructorArguments.Length >= 2)
            templateResourceName = attrData.ConstructorArguments[1].Value as string;

        return new PdfTemplateModel(
            typeSymbol.ToDisplayString(),
            typeSymbol.ContainingNamespace?.ToDisplayString() ?? string.Empty,
            typeSymbol.Name,
            templateId,
            templateResourceName,
            IsPartial: IsPartial(ctx.TargetNode),
            Location: typeSymbol.Locations.FirstOrDefault() ?? Location.None);
    }

    private static bool IsPartial(SyntaxNode node)
    {
        if (node is ClassDeclarationSyntax classDecl)
            return classDecl.Modifiers.Any(m => m.ValueText == "partial");
        if (node is RecordDeclarationSyntax recordDecl)
            return recordDecl.Modifiers.Any(m => m.ValueText == "partial");
        return false;
    }

    // -----------------------------------------------------------------------
    // EmitRenderer: produce the two source files per model
    // -----------------------------------------------------------------------

    private static void EmitRenderer(
        SourceProductionContext spc,
        PdfTemplateModel model,
        ImmutableArray<AdditionalText> additionalTexts)
    {
        // Emit PDFSG0002 if templateId is missing
        if (string.IsNullOrEmpty(model.TemplateId))
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                PdfTemplateGeneratorDiagnostics.EmptyTemplateId,
                model.Location,
                model.TypeName));
            return;
        }

        // Emit PDFSG0001 if class is not partial
        if (!model.IsPartial)
        {
            spc.ReportDiagnostic(Diagnostic.Create(
                PdfTemplateGeneratorDiagnostics.NotPartial,
                model.Location,
                model.TypeName));
        }

        // Resolve inlined HTML from AdditionalTexts (done at compile time — zero runtime cost)
        string inlinedHtmlExpression = BuildInlinedHtmlExpression(model, additionalTexts);

        EmitRendererClass(spc, model, inlinedHtmlExpression);
        EmitServiceExtensions(spc, model);
    }

    /// <summary>
    /// Builds the C# expression that represents the inlined HTML.
    /// - If templateResourceName is null: returns <c>""</c> (stub).
    /// - If AdditionalText found: returns an interpolated verbatim string with token substitution.
    /// - If AdditionalText NOT found: returns <c>""</c> with a comment.
    /// </summary>
    private static string BuildInlinedHtmlExpression(
        PdfTemplateModel model,
        ImmutableArray<AdditionalText> additionalTexts)
    {
        if (model.TemplateResourceName is null)
            return "\"\"";

        // Find matching AdditionalText by path suffix (case-insensitive path comparison)
        string? htmlContent = null;
        foreach (var text in additionalTexts)
        {
            if (text.Path.EndsWith(model.TemplateResourceName, StringComparison.OrdinalIgnoreCase) ||
                text.Path.EndsWith(model.TemplateResourceName.Replace('/', '\\'), StringComparison.OrdinalIgnoreCase))
            {
                htmlContent = text.GetText()?.ToString();
                break;
            }
        }

        if (htmlContent is null)
            return "\"\" /* template file not found in AdditionalTexts: " + EscapeComment(model.TemplateResourceName) + " */";

        return BuildInterpolatedHtml(htmlContent);
    }

    /// <summary>
    /// Converts HTML with {{Property}} tokens into a C# raw interpolated string.
    /// 1. Escape existing { and } that are NOT double-brace token delimiters.
    /// 2. Replace {{Word}} with {model.Word}.
    /// </summary>
    private static string BuildInterpolatedHtml(string html)
    {
        // Step 1: Replace {{Word}} tokens with a unique placeholder, then escape lone { / },
        // then restore placeholders as {model.Word}.

        // Collect all token positions first
        var tokenPattern = new Regex(@"\{\{(\w+)\}\}", RegexOptions.None);
        var matches = tokenPattern.Matches(html);

        // If no tokens exist and no { / } chars, use a plain string
        if (matches.Count == 0 && !html.Contains('{') && !html.Contains('}'))
        {
            return "@\"" + html.Replace("\"", "\"\"") + "\"";
        }

        // Build the interpolated string by processing the HTML character by character
        var sb = new StringBuilder();
        sb.Append("$@\"");

        int pos = 0;
        while (pos < html.Length)
        {
            // Check if we're at a {{Word}} token
            bool isToken = false;
            foreach (Match m in matches)
            {
                if (m.Index == pos)
                {
                    // Emit {model.PropertyName}
                    sb.Append('{');
                    sb.Append("model.");
                    sb.Append(m.Groups[1].Value);
                    sb.Append('}');
                    pos += m.Length;
                    isToken = true;
                    break;
                }
            }

            if (isToken) continue;

            char c = html[pos];
            if (c == '{')
            {
                // Check if it's the start of a {{Word}} token not caught above (shouldn't happen)
                // Escape lone { by doubling
                sb.Append("{{");
                pos++;
            }
            else if (c == '}')
            {
                // Escape lone } by doubling
                sb.Append("}}");
                pos++;
            }
            else if (c == '"')
            {
                // In verbatim @"", double quotes are escaped as ""
                sb.Append("\"\"");
                pos++;
            }
            else
            {
                sb.Append(c);
                pos++;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }

    private static string EscapeComment(string s) => s.Replace("*/", "* /");

    // -----------------------------------------------------------------------
    // Code emitters
    // -----------------------------------------------------------------------

    private static void EmitRendererClass(
        SourceProductionContext spc,
        PdfTemplateModel model,
        string inlinedHtmlExpression)
    {
        string fullTypeName = model.TypeFullName;
        string rendererClassName = model.TypeName + "PdfRenderer";
        string hintName = rendererClassName + ".g.cs";

        string source = $@"// <auto-generated />
// Generated by Muonroi.Pdf.SourceGenerators — do not edit manually.
#nullable enable
using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using global::Muonroi.Pdf.Abstractions;

namespace {model.TypeNamespace}.Generated
{{
    /// <summary>
    /// Compile-time generated PDF renderer for <see cref=""{EscapeXmlComment(fullTypeName)}""/>.
    /// Template HTML is inlined as C# string interpolation — no runtime resource loading.
    /// </summary>
    internal sealed class {rendererClassName} : global::Muonroi.Pdf.Abstractions.IMPdfRenderer<global::{fullTypeName}>
    {{
        private readonly global::Muonroi.Pdf.Abstractions.IMPdfService _service;

        public {rendererClassName}(global::Muonroi.Pdf.Abstractions.IMPdfService service)
        {{
            _service = service ?? throw new ArgumentNullException(nameof(service));
        }}

        /// <inheritdoc/>
        public string TemplateId => {QuoteString(model.TemplateId!)};

        /// <inheritdoc/>
        public Task<global::Muonroi.Pdf.Abstractions.PdfRenderResult> RenderAsync(
            global::{fullTypeName} model,
            Stream destination,
            global::Muonroi.Pdf.Abstractions.PdfRenderOptions? options = null,
            CancellationToken cancellationToken = default)
        {{
            string html = {inlinedHtmlExpression};
            return _service.RenderAsync(
                html,
                destination,
                options ?? new global::Muonroi.Pdf.Abstractions.PdfRenderOptions(),
                cancellationToken);
        }}
    }}
}}
";
        spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitServiceExtensions(SourceProductionContext spc, PdfTemplateModel model)
    {
        string fullTypeName = model.TypeFullName;
        string rendererClassName = model.TypeName + "PdfRenderer";
        string extensionMethodName = "AddPdfRenderer" + model.TypeName;
        string extensionsClassName = rendererClassName + "ServiceExtensions";
        string hintName = extensionsClassName + ".g.cs";

        string source = $@"// <auto-generated />
// Generated by Muonroi.Pdf.SourceGenerators — do not edit manually.
#nullable enable
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using global::Muonroi.Pdf.Abstractions;

namespace {model.TypeNamespace}.Generated
{{
    /// <summary>
    /// DI extension methods for the generated renderer for <see cref=""{EscapeXmlComment(fullTypeName)}""/>.
    /// </summary>
    internal static class {extensionsClassName}
    {{
        /// <summary>
        /// Registers <see cref=""{rendererClassName}""/> as the <see cref=""IMPdfRenderer{{TModel}}""/> implementation
        /// for <see cref=""{EscapeXmlComment(fullTypeName)}""/>. Uses TryAddSingleton — does not override an existing registration.
        /// </summary>
        public static IServiceCollection {extensionMethodName}(this IServiceCollection services)
        {{
            services.TryAddSingleton<
                global::Muonroi.Pdf.Abstractions.IMPdfRenderer<global::{fullTypeName}>,
                {rendererClassName}>();
            return services;
        }}
    }}
}}
";
        spc.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string QuoteString(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    private static string EscapeXmlComment(string s) => s.Replace("<", "{").Replace(">", "}");
}

// -----------------------------------------------------------------------
// Value model — must be equatable for incremental generator caching
// -----------------------------------------------------------------------

internal sealed record PdfTemplateModel(
    string TypeFullName,
    string TypeNamespace,
    string TypeName,
    string? TemplateId,
    string? TemplateResourceName,
    bool IsPartial,
    Location Location);
