global using FluentAssertions;
global using Microsoft.EntityFrameworkCore;
global using Muonroi.EntityFrameworkCore.Configuration;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using Xunit;
