apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muonroi-rule-engine.fullname" . }}
  labels:
    {{- include "muonroi-rule-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-connection-string: {{ include "muonroi-rule-engine.databaseConnectionString" . | quote }}
  redis-password: {{ include "muonroi-rule-engine.redisPassword" . | quote }}
