<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AsyncEnumerator" Version="4.0.2" />
    <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.14" />
    <PackageReference Include="Scriban" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.AspNetCore\Muonroi.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.AspNetCore.OpenApi\Muonroi.AspNetCore.OpenApi.csproj" />
  </ItemGroup>
</Project>
