<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AsyncEnumerator" />
    <PackageReference Include="Microsoft.Bcl.Memory" />
    <PackageReference Include="Scriban" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.AspNetCore\Muonroi.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.AspNetCore.OpenApi\Muonroi.AspNetCore.OpenApi.csproj" />
  </ItemGroup>
</Project>
