namespace Muonroi.Tenancy.SiteProfile.Web;

/// <summary>
/// Defines how the site migration runner behaves at startup.
/// </summary>
public enum MigrationStrategy
{
    /// <summary>
    /// Applies all pending EF Core migrations automatically at startup.
    /// Suitable for development and staging environments.
    /// </summary>
    AutoMigrate = 0,

    /// <summary>
    /// Checks for pending migrations and throws <see cref="InvalidOperationException"/>
    /// if any are found, without applying them.
    /// Suitable for production environments where migrations are applied via CI/CD.
    /// </summary>
    ValidateOnly = 1
}

/// <summary>
/// Configuration options for <see cref="SiteProfileDbContextExtensions.AddSiteMigrationRunner"/>.
/// Controls migration strategy, parallelism, and how site DbContext types are discovered.
///
/// <example>
/// Default (AutoMigrate, unbounded parallelism):
/// <code>
/// services.AddSiteMigrationRunner();
/// </code>
///
/// Production (ValidateOnly, capped parallelism):
/// <code>
/// services.AddSiteMigrationRunner(o =>
/// {
///     o.Strategy = MigrationStrategy.ValidateOnly; // check only, do not apply
///     o.MaxParallelism = 4;                        // limit concurrent migrations
/// });
/// </code>
///
/// Custom type provider (for consumers not using [GenerateSiteProfile]):
/// <code>
/// services.AddSiteMigrationRunner(o =>
/// {
///     o.DbContextTypeProvider = () => new[] { typeof(SiteADbContext), typeof(SiteBDbContext) };
/// });
/// </code>
/// </example>
/// </summary>
public sealed class SiteMigrationRunnerOptions
{
    /// <summary>
    /// Controls whether pending migrations are applied automatically or only validated.
    ///
    /// <list type="bullet">
    ///   <item><see cref="MigrationStrategy.AutoMigrate"/> — applies pending migrations at startup (default; use for dev/staging).</item>
    ///   <item><see cref="MigrationStrategy.ValidateOnly"/> — throws if pending migrations exist (use for production).</item>
    /// </list>
    ///
    /// Default: <see cref="MigrationStrategy.AutoMigrate"/>.
    /// </summary>
    public MigrationStrategy Strategy { get; set; } = MigrationStrategy.AutoMigrate;

    /// <summary>
    /// Maximum number of DbContexts to migrate in parallel.
    ///
    /// <list type="bullet">
    ///   <item><c>0</c> (default) — unbounded; uses <see cref="Environment.ProcessorCount"/>.</item>
    ///   <item>Any positive value — caps concurrent migrations to that number.</item>
    /// </list>
    ///
    /// Example: <c>MaxParallelism = 4</c> migrates at most 4 DbContexts simultaneously.
    /// </summary>
    public int MaxParallelism { get; set; } = 0;

    /// <summary>
    /// Optional override for how site DbContext types are discovered.
    ///
    /// When <c>null</c> (default), the runner discovers <c>SiteDbContextTypeRegistry.GetAllSiteDbContextTypes()</c>
    /// from the consumer assembly via reflection — the type generated by <c>[GenerateSiteProfile]</c>.
    ///
    /// Set this if the consumer does not use <c>[GenerateSiteProfile]</c> and wants to provide
    /// DbContext types explicitly.
    ///
    /// Examples:
    /// - Manual: <c>() => new[] { typeof(SiteADbContext), typeof(SiteBDbContext) }</c>
    /// - Dynamic from config: <c>() => typeResolver.GetConfiguredContextTypes()</c>
    /// </summary>
    public Func<IReadOnlyList<Type>>? DbContextTypeProvider { get; set; }
}
