using Muonroi.Core.Abstractions.Exceptions;
using System.Diagnostics;
using Microsoft.Extensions.Hosting;
using Muonroi.Logging.Abstractions;

namespace Muonroi.Tenancy.SiteProfile.Web;

/// <summary>
/// IHostedService that discovers all site DbContext types at startup and applies (or validates)
/// EF Core migrations in parallel. Registered via
/// <see cref="SiteProfileDbContextExtensions.AddSiteMigrationRunner"/>.
///
/// Type discovery order:
/// 1. <see cref="SiteMigrationRunnerOptions.DbContextTypeProvider"/> if set (explicit override).
/// 2. Reflection scan for <c>Muonroi.Tenancy.SiteProfile.Generated.SiteDbContextTypeRegistry</c>
///    generated by <c>[GenerateSiteProfile]</c> (Plan 50-01).
/// 3. If neither is available, logs a warning and exits without error.
/// </summary>
internal sealed class SiteMigrationRunner(
    IServiceProvider serviceProvider,
    SiteMigrationRunnerOptions options,
    IMLog<SiteMigrationRunner> log) : IHostedService
{
    public async Task StartAsync(CancellationToken cancellationToken)
    {
        // -----------------------------------------------------------------------
        // Step 1: Discover site DbContext types
        // -----------------------------------------------------------------------
        IReadOnlyList<Type> dbContextTypes;

        if (options.DbContextTypeProvider is not null)
        {
            dbContextTypes = options.DbContextTypeProvider.Invoke();
        }
        else
        {
            // Scan loaded assemblies for the source-generated SiteDbContextTypeRegistry type.
            // The registry lives in the consumer's assembly — we cannot reference it directly.
            Type? registryType = AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(a =>
                {
                    try { return a.GetTypes(); }
                    catch { return Array.Empty<Type>(); }
                })
                .FirstOrDefault(t =>
                    t.Name == "SiteDbContextTypeRegistry" &&
                    t.Namespace == "Muonroi.Tenancy.SiteProfile.Generated");

            if (registryType is null)
            {
                log.Warn(
                    "[SiteMigration] SiteDbContextTypeRegistry not found in any loaded assembly. " +
                    "Ensure [GenerateSiteProfile] is applied, or set SiteMigrationRunnerOptions.DbContextTypeProvider. " +
                    "Migration runner will not run.");
                return;
            }

            var getTypesMethod = registryType.GetMethod(
                "GetAllSiteDbContextTypes",
                System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Static);

            if (getTypesMethod is null)
            {
                log.Warn(
                    "[SiteMigration] GetAllSiteDbContextTypes() not found on SiteDbContextTypeRegistry. " +
                    "Migration runner will not run.");
                return;
            }

            var result = getTypesMethod.Invoke(null, null);
            dbContextTypes = result as IReadOnlyList<Type> ?? Array.Empty<Type>();
        }

        if (dbContextTypes.Count == 0)
        {
            log.Info("[SiteMigration] No site DbContext types discovered — nothing to migrate.");
            return;
        }

        var typeNames = string.Join(", ", dbContextTypes.Select(t => t.Name));
        log.Info("[SiteMigration] Discovered {Count} site DbContext type(s): {TypeNames}",
            dbContextTypes.Count, typeNames);

        // -----------------------------------------------------------------------
        // Step 2: Determine effective parallelism
        // -----------------------------------------------------------------------
        int effectiveParallelism = options.MaxParallelism <= 0
            ? Environment.ProcessorCount
            : options.MaxParallelism;

        // -----------------------------------------------------------------------
        // Step 3: Execute migration strategy
        // -----------------------------------------------------------------------
        var sw = Stopwatch.StartNew();
        var failures = new System.Collections.Concurrent.ConcurrentBag<string>();

        var parallelOptions = new ParallelOptions
        {
            MaxDegreeOfParallelism = effectiveParallelism,
            CancellationToken = cancellationToken
        };

        if (options.Strategy == MigrationStrategy.AutoMigrate)
        {
            await Parallel.ForEachAsync(dbContextTypes, parallelOptions, async (dbContextType, ct) =>
            {
                try
                {
                    using IServiceScope scope = serviceProvider.CreateScope();
                    if (scope.ServiceProvider.GetRequiredService(dbContextType) is not DbContext dbContext)
                    {
                        failures.Add($"{dbContextType.Name} could not be resolved as DbContext");
                        return;
                    }

                    await dbContext.Database.MigrateAsync(ct).ConfigureAwait(false);
                    log.Info("[SiteMigration] Migrated {TypeName} successfully", dbContextType.Name);
                }
                catch (Exception ex)
                {
                    log.Error(ex, "[SiteMigration] Failed to migrate {TypeName}: {Message}",
                        dbContextType.Name, ex.Message);
                    failures.Add($"{dbContextType.Name}: {ex.Message}");
                }
            }).ConfigureAwait(false);

            if (failures.Count > 0)
            {
                throw new AggregateException(
                    $"[SiteMigration] {failures.Count} DbContext(s) failed to migrate.",
                    failures.Select(f => new InvalidOperationException(f)));
            }
        }
        else // ValidateOnly
        {
            await Parallel.ForEachAsync(dbContextTypes, parallelOptions, async (dbContextType, ct) =>
            {
                try
                {
                    using IServiceScope scope = serviceProvider.CreateScope();
                    if (scope.ServiceProvider.GetRequiredService(dbContextType) is not DbContext dbContext)
                    {
                        failures.Add($"{dbContextType.Name} could not be resolved as DbContext");
                        return;
                    }

                    IEnumerable<string> pending =
                        await dbContext.Database.GetPendingMigrationsAsync(ct).ConfigureAwait(false);

                    string[] pendingArray = [.. pending];
                    if (pendingArray.Length > 0)
                    {
                        string names = string.Join(", ", pendingArray);
                        failures.Add(
                            $"{dbContextType.Name} has {pendingArray.Length} pending migration(s): {names}");
                    }
                    else
                    {
                        log.Info("[SiteMigration] Validated {TypeName} — no pending migrations",
                            dbContextType.Name);
                    }
                }
                catch (Exception ex)
                {
                    log.Error(ex, "[SiteMigration] Failed to validate {TypeName}: {Message}",
                        dbContextType.Name, ex.Message);
                    failures.Add($"{dbContextType.Name}: {ex.Message}");
                }
            }).ConfigureAwait(false);

            if (failures.Count > 0)
            {
                string details = string.Join("\n  - ", failures);
                throw new MInternalException(
                    $"[SiteMigration] Pending migrations detected — deployment must apply migrations before starting:\n  - {details}");
            }
        }

        sw.Stop();
        log.Info(
            "[SiteMigration] Completed — {Strategy} for {Count} DbContext(s) in {ElapsedMs}ms",
            options.Strategy, dbContextTypes.Count, sw.ElapsedMilliseconds);
    }

    public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;
}
