<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>Muonroi.Tenancy.Extended.Tests</AssemblyName>
  </PropertyGroup>
<ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.Tenancy\Muonroi.Tenancy.csproj" />
  </ItemGroup>
</Project>