<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Consul" />
<PackageReference Include="Moq" />
</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.ServiceDiscovery.Consul\Muonroi.ServiceDiscovery.Consul.csproj" />
  </ItemGroup>
</Project>