using Muonroi.RuleEngine.SourceGenerators.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Muonroi.RuleEngine.SourceGenerators.SourceWriters;

internal static class GeneratedRuleSourceWriter
{
    public static string Render(ExtractedRuleDefinition definition)
    {
        string className = $"{ToIdentifier(definition.Code)}Rule";
        (string dependencyFields, string dependencyCtor) = RenderDependencyConstructor(className, definition.Dependencies);
        string dependenciesProperty = RenderDependenciesProperty(definition.Dependencies);
        string dependsOn = definition.DependsOn.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", definition.DependsOn.Select(value => $"\"{Escape(value)}\""))} }}";

        string[] localFunction = RenderLocalFunction(definition);
        string[] helperMethods = RenderHelperMethods(definition.HelperMethods);
        string[] invokeLogic = RenderInvokeLogic(definition);

        HashSet<string> usings = new(StringComparer.Ordinal)
        {
            "System",
            "System.Collections.Generic",
            "System.Reflection",
            "System.Threading",
            "System.Threading.Tasks",
            "Muonroi.RuleEngine.Abstractions"
        };

        foreach (string usingDirective in definition.Usings)
        {
            if (!string.IsNullOrWhiteSpace(usingDirective) && !usingDirective.StartsWith("Muonroi.RuleEngine.Abstractions", StringComparison.Ordinal))
            {
                usings.Add(usingDirective);
            }
        }

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}"); // MBB001-exempt: Roslyn source generator (netstandard2.0) - no DI available

        foreach (string usingDirective in usings.OrderBy(value => value, StringComparer.Ordinal))
        {
            builder.AppendLine($"using {usingDirective};");
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {definition.OutputNamespace};");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(definition.DocumentationComment))
        {
            builder.AppendLine(definition.DocumentationComment);
        }

        builder.AppendLine($"public sealed class {className} : IRule<{definition.ContextType}>");
        builder.AppendLine("{");

        if (!string.IsNullOrWhiteSpace(dependencyFields))
        {
            builder.AppendLine(dependencyFields);
            builder.AppendLine();
            builder.AppendLine(dependencyCtor);
            builder.AppendLine();
        }

        builder.AppendLine($"    public string Code => \"{Escape(definition.Code)}\";");
        builder.AppendLine($"    public int Order => {definition.Order};");
        builder.AppendLine($"    public IReadOnlyList<string> DependsOn => {dependsOn};");
        builder.AppendLine($"    public HookPoint HookPoint => HookPoint.{definition.HookPoint};");
        builder.AppendLine("    public RuleType Type => RuleType.Validation;");
        builder.AppendLine($"    public string Name => \"{Escape(className)}\";");
        builder.AppendLine($"    public IEnumerable<System.Type> Dependencies => {dependenciesProperty};");
        builder.AppendLine();

        foreach (string attribute in definition.CustomAttributes)
        {
            builder.AppendLine($"    {attribute}");
        }

        builder.AppendLine($"    public async Task<RuleResult> EvaluateAsync({definition.ContextType} ctx, FactBag facts, CancellationToken ct)");
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");

        foreach (string line in localFunction)
        {
            builder.AppendLine($"            {line}");
        }

        if (localFunction.Length > 0)
        {
            builder.AppendLine();
        }

        foreach (string line in invokeLogic)
        {
            builder.AppendLine($"            {line}");
        }

        builder.AppendLine("        }");
        builder.AppendLine("        catch (Exception ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return RuleResult.Failure(ex.Message);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine($"    public Task ExecuteAsync({definition.ContextType} context, CancellationToken cancellationToken = default)");
        builder.AppendLine("    {");
        builder.AppendLine("        return Task.CompletedTask;");
        builder.AppendLine("    }");

        foreach (string line in helperMethods)
        {
            builder.AppendLine(line);
        }

        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            foreach (string line in RenderFeelHelpers(definition))
            {
                builder.AppendLine(line);
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static (string Fields, string Constructor) RenderDependencyConstructor(string className, IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return (string.Empty, string.Empty);
        }

        string fields = string.Join("\n", dependencies.Select(dependency => $"    private readonly {dependency.TypeName} {dependency.FieldName};"));
        string args = string.Join(", ", dependencies.Select(dependency => $"{dependency.TypeName} {dependency.ConstructorParameterName}"));
        string assigns = string.Join("\n", dependencies.Select(dependency => $"        {dependency.FieldName} = {dependency.ConstructorParameterName};"));
        string constructor = "    public " + className + "(" + args + ")" + "\n"
            + "    {" + "\n"
            + assigns + "\n"
            + "    }";
        return (fields, constructor);
    }

    private static string[] RenderHelperMethods(IReadOnlyList<HelperMethodDefinition> helpers)
    {
        if (helpers.Count == 0)
        {
            return Array.Empty<string>();
        }

        List<string> lines = [];
        foreach (HelperMethodDefinition helper in helpers)
        {
            lines.Add(string.Empty);
            string asyncModifier = helper.IsAsync ? "async " : string.Empty;
            string parameters = string.Join(", ", helper.Parameters.Select(RenderParameter));
            lines.Add($"    private static {asyncModifier}{helper.ReturnType} {helper.MethodName}({parameters})");
            lines.Add("    {");

            if (!string.IsNullOrWhiteSpace(helper.MethodBody))
            {
                foreach (string line in GetBlockBodyLines(helper.MethodBody ?? string.Empty))
                {
                    lines.Add($"        {line}");
                }
            }
            else if (!string.IsNullOrWhiteSpace(helper.ExpressionBody))
            {
                lines.Add($"        return {helper.ExpressionBody};");
            }
            else
            {
                lines.Add("        return default!;");
            }

            lines.Add("    }");
        }

        return lines.ToArray();
    }

    private static string[] RenderLocalFunction(ExtractedRuleDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            return Array.Empty<string>();
        }

        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string parameterList = string.Join(", ", definition.Parameters.Select(RenderParameter));
        string asyncModifier = definition.IsAsync ? "async " : string.Empty;

        List<string> lines =
        [
            $"{asyncModifier}{definition.ReturnType} {localName}({parameterList})",
            "{"
        ];

        if (!string.IsNullOrWhiteSpace(definition.MethodBody))
        {
            foreach (string line in GetBlockBodyLines(definition.MethodBody ?? string.Empty))
            {
                lines.Add($"    {line}");
            }
        }
        else if (!string.IsNullOrWhiteSpace(definition.ExpressionBody))
        {
            lines.Add($"    return {definition.ExpressionBody};");
        }
        else
        {
            lines.Add("    return default!;");
        }

        lines.Add("}");
        return lines.ToArray();
    }

    private static string[] RenderInvokeLogic(ExtractedRuleDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            string escapedExpression = definition.FeelExpression!.Replace("\"", "\"\"");
            return
            [
                $"var __feelVars = BuildFeelVariables(ctx, facts);",
                $"var __compiled = global::Muonroi.RuleEngine.Runtime.Compilation.Feel.FeelExpressionCompiler.Compile(@\"{escapedExpression}\");",
                "var __ok = __compiled(__feelVars);",
                "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"
            ];
        }

        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string args = string.Join(", ", definition.Parameters.Select(parameter => MapInvocationArgument(parameter, definition.ContextType)));
        string returnType = definition.ReturnType.Replace(" ", string.Empty);

        if (returnType == "Task<RuleResult>")
        {
            return [$"var __result = await {localName}({args});", "return __result;"];
        }

        if (returnType == "RuleResult")
        {
            return [$"var __result = {localName}({args});", "return __result;"];
        }

        if (returnType == "Task<bool>")
        {
            return [$"var __ok = await {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"];
        }

        if (returnType == "bool")
        {
            return [$"var __ok = {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"];
        }

        if (returnType == "Task")
        {
            return [$"await {localName}({args});", "return RuleResult.Passed();"];
        }

        if (returnType == "void")
        {
            return [$"{localName}({args});", "return RuleResult.Passed();"];
        }

        if (returnType.StartsWith("Task<", StringComparison.Ordinal))
        {
            return
            [
                $"var __value = await {localName}({args});",
                $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
                "return RuleResult.Passed();"
            ];
        }

        return
        [
            $"var __value = {localName}({args});",
            $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
            "return RuleResult.Passed();"
        ];
    }

    private static IEnumerable<string> RenderFeelHelpers(ExtractedRuleDefinition definition)
    {
        string contextType = definition.ContextType;
        return
        [
            string.Empty,
            $"    private static Dictionary<string, object> BuildFeelVariables({contextType} ctx, FactBag facts)",
            "    {",
            "        Dictionary<string, object> vars = new(StringComparer.OrdinalIgnoreCase);",
            "        if (ctx is not null)",
            "        {",
            "            foreach (PropertyInfo property in typeof(" + contextType + ").GetProperties(BindingFlags.Instance | BindingFlags.Public))",
            "            {",
            "                if (!property.CanRead)",
            "                {",
            "                    continue;",
            "                }",
            "",
            "                object? value = property.GetValue(ctx);",
            "                if (value is not null)",
            "                {",
            "                    vars[property.Name] = value;",
            "                    vars[char.ToLowerInvariant(property.Name[0]) + property.Name.Substring(1)] = value;",
            "                }",
            "            }",
            "        }",
            "",
            "        foreach (string key in facts.Keys)",
            "        {",
            "            object? value = facts.Get<object>(key);",
            "            if (value is not null)",
            "            {",
            "                vars[key] = value;",
            "            }",
            "        }",
            "",
            "        return vars;",
            "    }"
        ];
    }

    private static string RenderDependenciesProperty(IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return "Array.Empty<System.Type>()";
        }

        string types = string.Join(", ", dependencies.Select(dependency => $"typeof({dependency.TypeName})"));
        return $"new[] {{ {types} }}";
    }

    private static string MapInvocationArgument(ParameterModel parameter, string contextType)
    {
        string typeName = parameter.TypeName.Replace(" ", string.Empty);
        if (typeName is "FactBag" or "Muonroi.RuleEngine.Abstractions.FactBag")
        {
            return "facts";
        }

        if (typeName is "CancellationToken" or "System.Threading.CancellationToken")
        {
            return "ct";
        }

        if (string.Equals(typeName, contextType.Replace(" ", string.Empty), StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "ctx", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "context", StringComparison.OrdinalIgnoreCase))
        {
            return "ctx";
        }

        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return parameter.DefaultValueExpression!;
        }

        return "default!";
    }

    private static string RenderParameter(ParameterModel parameter)
    {
        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueExpression}";
        }

        return $"{parameter.TypeName} {parameter.Name}";
    }

    private static string ToIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "GeneratedRule";
        }

        char[] chars = value.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray();
        string normalized = new(chars);
        if (!char.IsLetter(normalized[0]) && normalized[0] != '_')
        {
            normalized = "R_" + normalized;
        }

        return normalized;
    }

    private static string Escape(string text)
    {
        return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string[] GetBlockBodyLines(string bodyText)
    {
        if (string.IsNullOrWhiteSpace(bodyText))
        {
            return Array.Empty<string>();
        }

        string normalized = bodyText.Trim();
        if (normalized.StartsWith("{", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(1);
        }

        if (normalized.EndsWith("}", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(0, normalized.Length - 1);
        }

        return normalized
            .Split(new[] { "\r\n", "\n" }, StringSplitOptions.None)
            .Select(line => line.TrimEnd())
            .Where(line => line.Length > 0)
            .ToArray();
    }
}
