using Muonroi.RuleEngine.SourceGenerators.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Muonroi.RuleEngine.SourceGenerators.SourceWriters;

internal static class GeneratedRuleSourceWriter
{
    public static string Render(ExtractedRuleDefinition definition)
    {
        string className = $"{ToIdentifier(definition.Code)}Rule";
        (string dependencyFields, string dependencyCtor) = RenderDependencyConstructor(className, definition.Dependencies);
        string dependenciesProperty = RenderDependenciesProperty(definition.Dependencies);
        string dependsOn = definition.DependsOn.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", definition.DependsOn.Select(value => $"\"{Escape(value)}\""))} }}";

        string[] localFunction = RenderLocalFunction(definition);
        string[] helperMethods = RenderHelperMethods(definition.HelperMethods, definition.UseFactBagAware);
        string[] invokeLogic = RenderInvokeLogic(definition);

        HashSet<string> usings = new(StringComparer.Ordinal)
        {
            "System",
            "System.Collections.Generic",
            "System.Reflection",
            "System.Threading",
            "System.Threading.Tasks",
            "Muonroi.RuleEngine.Abstractions"
        };

        foreach (string usingDirective in definition.Usings)
        {
            if (!string.IsNullOrWhiteSpace(usingDirective) && !usingDirective.StartsWith("Muonroi.RuleEngine.Abstractions", StringComparison.Ordinal))
            {
                usings.Add(usingDirective);
            }
        }

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}"); // MBB001-exempt: Roslyn source generator (netstandard2.0) - no DI available

        foreach (string usingDirective in usings.OrderBy(value => value, StringComparer.Ordinal))
        {
            builder.AppendLine($"using {usingDirective};");
        }

        builder.AppendLine();
        builder.AppendLine($"namespace {definition.OutputNamespace};");
        builder.AppendLine();

        if (!string.IsNullOrWhiteSpace(definition.DocumentationComment))
        {
            builder.AppendLine(definition.DocumentationComment);
        }

        string baseType = definition.UseFactBagAware
            ? "MFactBagAwareRule<" + definition.ContextType + ">"
            : "IRule<" + definition.ContextType + ">";
        builder.AppendLine("public sealed class " + className + " : " + baseType);
        builder.AppendLine("{");

        if (!string.IsNullOrWhiteSpace(dependencyFields))
        {
            builder.AppendLine(dependencyFields);
            builder.AppendLine();
            builder.AppendLine(dependencyCtor);
            builder.AppendLine();
        }

        string propMod = definition.UseFactBagAware ? "override " : "";
        builder.AppendLine("    public " + propMod + "string Code => \"" + Escape(definition.Code) + "\";");
        builder.AppendLine("    public " + propMod + "int Order => " + definition.Order + ";");
        builder.AppendLine("    public " + propMod + "IReadOnlyList<string> DependsOn => " + dependsOn + ";");
        builder.AppendLine("    public " + propMod + "HookPoint HookPoint => HookPoint." + definition.HookPoint + ";");
        builder.AppendLine("    public " + propMod + "RuleType Type => RuleType.Validation;");
        builder.AppendLine("    public " + propMod + "string Name => \"" + Escape(className) + "\";");
        builder.AppendLine("    public " + propMod + "IEnumerable<System.Type> Dependencies => " + dependenciesProperty + ";");
        builder.AppendLine();

        foreach (string attribute in definition.CustomAttributes)
        {
            builder.AppendLine($"    {attribute}");
        }

        if (definition.UseFactBagAware)
        {
            builder.AppendLine("    protected async override Task<RuleResult> EvaluateCoreAsync(" + definition.ContextType + " ctx, CancellationToken ct)");
        }
        else
        {
            builder.AppendLine("    public async Task<RuleResult> EvaluateAsync(" + definition.ContextType + " ctx, FactBag facts, CancellationToken ct)");
        }
        builder.AppendLine("    {");
        builder.AppendLine("        try");
        builder.AppendLine("        {");
        builder.AppendLine("            await Task.CompletedTask;");

        foreach (string line in localFunction)
        {
            builder.AppendLine("            " + line);
        }

        if (localFunction.Length > 0)
        {
            builder.AppendLine();
        }

        foreach (string line in invokeLogic)
        {
            builder.AppendLine("            " + line);
        }

        builder.AppendLine("        }");
        builder.AppendLine("        catch (Exception ex)");
        builder.AppendLine("        {");
        builder.AppendLine("            return RuleResult.Failure(ex.Message);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");

        if (!definition.UseFactBagAware)
        {
            builder.AppendLine();
            builder.AppendLine("    public Task ExecuteAsync(" + definition.ContextType + " context, CancellationToken cancellationToken = default)");
            builder.AppendLine("    {");
            builder.AppendLine("        return Task.CompletedTask;");
            builder.AppendLine("    }");
        }

        foreach (string line in helperMethods)
        {
            builder.AppendLine(line);
        }

        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            foreach (string line in RenderFeelHelpers(definition))
            {
                builder.AppendLine(line);
            }
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static (string Fields, string Constructor) RenderDependencyConstructor(string className, IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return (string.Empty, string.Empty);
        }

        string fields = string.Join("\n", dependencies.Select(dependency => $"    private readonly {dependency.TypeName} {dependency.FieldName};"));
        string args = string.Join(", ", dependencies.Select(dependency => $"{dependency.TypeName} {dependency.ConstructorParameterName}"));
        string assigns = string.Join("\n", dependencies.Select(dependency => $"        {dependency.FieldName} = {dependency.ConstructorParameterName};"));
        string constructor = "    public " + className + "(" + args + ")" + "\n"
            + "    {" + "\n"
            + assigns + "\n"
            + "    }";
        return (fields, constructor);
    }

    private static string[] RenderHelperMethods(IReadOnlyList<HelperMethodDefinition> helpers, bool useFactBagAware = false)
    {
        if (helpers.Count == 0)
        {
            return Array.Empty<string>();
        }

        List<string> lines = [];
        foreach (HelperMethodDefinition helper in helpers)
        {
            lines.Add(string.Empty);
            string asyncModifier = helper.IsAsync ? "async " : string.Empty;
            string parameters = string.Join(", ", helper.Parameters.Select(RenderParameter));
            lines.Add("    private static " + asyncModifier + helper.ReturnType + " " + helper.MethodName + "(" + parameters + ")");
            lines.Add("    {");

            if (!string.IsNullOrWhiteSpace(helper.MethodBody))
            {
                foreach (string line in GetBlockBodyLines(helper.MethodBody ?? string.Empty))
                {
                    lines.Add("        " + (useFactBagAware ? TransformBodyForFactBagAware(line) : line));
                }
            }
            else if (!string.IsNullOrWhiteSpace(helper.ExpressionBody))
            {
                string expr = helper.ExpressionBody!;
                if (useFactBagAware)
                {
                    expr = TransformBodyForFactBagAware(expr);
                }
                lines.Add("        return " + expr + ";");
            }
            else
            {
                lines.Add("        return default!;");
            }

            lines.Add("    }");
        }

        return [.. lines];
    }

    private static string[] RenderLocalFunction(ExtractedRuleDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            return Array.Empty<string>();
        }

        string localName = "__source_" + ToIdentifier(definition.MethodName);
        IEnumerable<ParameterModel> parameters = definition.UseFactBagAware
            ? definition.Parameters.Where(p => !IsFactBag(p.TypeName))
            : definition.Parameters;
        string parameterList = string.Join(", ", parameters.Select(RenderParameter));
        string asyncModifier = definition.IsAsync ? "async " : string.Empty;

        List<string> lines =
        [
            asyncModifier + definition.ReturnType + " " + localName + "(" + parameterList + ")",
            "{"
        ];

        if (!string.IsNullOrWhiteSpace(definition.MethodBody))
        {
            foreach (string line in GetBlockBodyLines(definition.MethodBody ?? string.Empty))
            {
                lines.Add("    " + (definition.UseFactBagAware ? TransformBodyForFactBagAware(line) : line));
            }
        }
        else if (!string.IsNullOrWhiteSpace(definition.ExpressionBody))
        {
            string expr = definition.ExpressionBody!;
            if (definition.UseFactBagAware)
            {
                expr = TransformBodyForFactBagAware(expr);
            }
            lines.Add("    return " + expr + ";");
        }
        else
        {
            lines.Add("    return default!;");
        }

        lines.Add("}");
        return [.. lines];
    }

    private static bool IsFactBag(string typeName)
    {
        return typeName.IndexOf("FactBag", StringComparison.Ordinal) >= 0;
    }

    private static string TransformBodyForFactBagAware(string line)
    {
        return line
            .Replace("facts.Get<", "ReadFact<")
            .Replace("facts.Set(", "WriteFact(")
            .Replace("facts.Set<", "WriteFact<")
            .Replace("facts.TryGet<", "Facts.TryGet<");
    }

    private static string[] RenderInvokeLogic(ExtractedRuleDefinition definition)
    {
        if (!string.IsNullOrWhiteSpace(definition.FeelExpression))
        {
            string escapedExpression = definition.FeelExpression!.Replace("\"", "\"\"");
            return
            [
                $"var __feelVars = BuildFeelVariables(ctx, facts);",
                $"var __compiled = global::Muonroi.RuleEngine.Runtime.Compilation.Feel.FeelExpressionCompiler.Compile(@\"{escapedExpression}\");",
                "var __ok = __compiled(__feelVars);",
                "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"
            ];
        }

        string localName = "__source_" + ToIdentifier(definition.MethodName);
        IEnumerable<ParameterModel> invokeParams = definition.UseFactBagAware
            ? definition.Parameters.Where(p => !IsFactBag(p.TypeName))
            : definition.Parameters;
        string args = string.Join(", ", invokeParams.Select(parameter => MapInvocationArgument(parameter, definition.ContextType)));
        string returnType = definition.ReturnType.Replace(" ", string.Empty);

        if (returnType == "Task<RuleResult>")
        {
            return [$"var __result = await {localName}({args});", "return __result;"];
        }

        if (returnType == "RuleResult")
        {
            return [$"var __result = {localName}({args});", "return __result;"];
        }

        if (returnType == "Task<bool>")
        {
            return [$"var __ok = await {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"];
        }

        if (returnType == "bool")
        {
            return [$"var __ok = {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"];
        }

        if (returnType == "Task")
        {
            return [$"await {localName}({args});", "return RuleResult.Passed();"];
        }

        if (returnType == "void")
        {
            return [$"{localName}({args});", "return RuleResult.Passed();"];
        }

        if (returnType.StartsWith("Task<", StringComparison.Ordinal))
        {
            string storeResult = definition.UseFactBagAware
                ? "WriteFact(\"" + Escape(definition.Code) + ":result\", __value);"
                : "facts[\"" + Escape(definition.Code) + ":result\"] = __value;";
            return
            [
                "var __value = await " + localName + "(" + args + ");",
                storeResult,
                "return RuleResult.Passed();"
            ];
        }

        {
            string storeResult = definition.UseFactBagAware
                ? "WriteFact(\"" + Escape(definition.Code) + ":result\", __value);"
                : "facts[\"" + Escape(definition.Code) + ":result\"] = __value;";
            return
            [
                "var __value = " + localName + "(" + args + ");",
                storeResult,
                "return RuleResult.Passed();"
            ];
        }
    }

    private static IEnumerable<string> RenderFeelHelpers(ExtractedRuleDefinition definition)
    {
        string contextType = definition.ContextType;
        return
        [
            string.Empty,
            $"    private static Dictionary<string, object> BuildFeelVariables({contextType} ctx, FactBag facts)",
            "    {",
            "        Dictionary<string, object> vars = new(StringComparer.OrdinalIgnoreCase);",
            "        if (ctx is not null)",
            "        {",
            "            foreach (PropertyInfo property in typeof(" + contextType + ").GetProperties(BindingFlags.Instance | BindingFlags.Public))",
            "            {",
            "                if (!property.CanRead)",
            "                {",
            "                    continue;",
            "                }",
            "",
            "                object? value = property.GetValue(ctx);",
            "                if (value is not null)",
            "                {",
            "                    vars[property.Name] = value;",
            "                    vars[char.ToLowerInvariant(property.Name[0]) + property.Name.Substring(1)] = value;",
            "                }",
            "            }",
            "        }",
            "",
            "        foreach (string key in facts.Keys)",
            "        {",
            "            object? value = facts.Get<object>(key);",
            "            if (value is not null)",
            "            {",
            "                vars[key] = value;",
            "            }",
            "        }",
            "",
            "        return vars;",
            "    }"
        ];
    }

    private static string RenderDependenciesProperty(IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return "Array.Empty<System.Type>()";
        }

        string types = string.Join(", ", dependencies.Select(dependency => $"typeof({dependency.TypeName})"));
        return $"new[] {{ {types} }}";
    }

    private static string MapInvocationArgument(ParameterModel parameter, string contextType)
    {
        string typeName = parameter.TypeName.Replace(" ", string.Empty);
        if (typeName is "FactBag" or "Muonroi.RuleEngine.Abstractions.FactBag")
        {
            return "facts";
        }

        if (typeName is "CancellationToken" or "System.Threading.CancellationToken")
        {
            return "ct";
        }

        if (string.Equals(typeName, contextType.Replace(" ", string.Empty), StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "ctx", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "context", StringComparison.OrdinalIgnoreCase))
        {
            return "ctx";
        }

        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return parameter.DefaultValueExpression!;
        }

        return "default!";
    }

    private static string RenderParameter(ParameterModel parameter)
    {
        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueExpression}";
        }

        return $"{parameter.TypeName} {parameter.Name}";
    }

    private static string ToIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "GeneratedRule";
        }

        char[] chars = [.. value.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_')];
        string normalized = new(chars);
        if (!char.IsLetter(normalized[0]) && normalized[0] != '_')
        {
            normalized = "R_" + normalized;
        }

        return normalized;
    }

    private static string Escape(string text)
    {
        return text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string[] GetBlockBodyLines(string bodyText)
    {
        if (string.IsNullOrWhiteSpace(bodyText))
        {
            return Array.Empty<string>();
        }

        string normalized = bodyText.Trim();
        if (normalized.StartsWith("{", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(1);
        }

        if (normalized.EndsWith("}", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(0, normalized.Length - 1);
        }

        return [.. normalized
            .Split(new[] { "\r\n", "\n" }, StringSplitOptions.None)
            .Select(line => line.TrimEnd())
            .Where(line => line.Length > 0)];
    }
}
