using Muonroi.RuleEngine.SourceGenerators.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Muonroi.RuleEngine.SourceGenerators.SourceWriters;

internal static class GeneratedRuleSourceWriter
{
    public static string Render(ExtractedRuleDefinition definition)
    {
        string className = $"{ToIdentifier(definition.Code)}Rule";
        (string dependencyFields, string dependencyCtor) = RenderDependencyConstructor(className, definition.Dependencies);
        string dependenciesProperty = RenderDependenciesProperty(definition.Dependencies);
        string dependsOn = definition.DependsOn.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", definition.DependsOn.Select(v => $"\"{Escape(v)}\""))} }}";

        string[] localFunction = RenderLocalFunction(definition);
        string[] helperMethods = RenderHelperMethods(definition.HelperMethods);
        string[] invokeLogic = RenderInvokeLogic(definition);

        HashSet<string> usings = new(StringComparer.Ordinal)
        {
            "System",
            "System.Collections.Generic",
            "System.Threading",
            "System.Threading.Tasks",
            "Muonroi.RuleEngine.Abstractions"
        };

        foreach (string u in definition.Usings)
        {
            if (!string.IsNullOrWhiteSpace(u) && !u.StartsWith("Muonroi.RuleEngine.Abstractions", StringComparison.Ordinal))
            {
                usings.Add(u);
            }
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}"); // MBB001-exempt: Roslyn source generator (netstandard2.0) — no DI available

        foreach (string u in usings.OrderBy(x => x, StringComparer.Ordinal))
        {
            sb.AppendLine($"using {u};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {definition.OutputNamespace};");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(definition.DocumentationComment))
        {
            sb.AppendLine(definition.DocumentationComment);
        }

        sb.AppendLine($"public sealed class {className} : IRule<{definition.ContextType}>");
        sb.AppendLine("{");

        if (!string.IsNullOrWhiteSpace(dependencyFields))
        {
            sb.AppendLine(dependencyFields);
            sb.AppendLine();
            sb.AppendLine(dependencyCtor);
            sb.AppendLine();
        }

        sb.AppendLine($"    public string Code => \"{Escape(definition.Code)}\";");
        sb.AppendLine($"    public int Order => {definition.Order};");
        sb.AppendLine($"    public IReadOnlyList<string> DependsOn => {dependsOn};");
        sb.AppendLine($"    public HookPoint HookPoint => HookPoint.{definition.HookPoint};");
        sb.AppendLine("    public RuleType Type => RuleType.Validation;");
        sb.AppendLine($"    public string Name => \"{Escape(className)}\";");
        sb.AppendLine($"    public IEnumerable<System.Type> Dependencies => {dependenciesProperty};");
        sb.AppendLine();

        foreach (string attr in definition.CustomAttributes)
        {
            sb.AppendLine($"    {attr}");
        }

        sb.AppendLine($"    public async Task<RuleResult> EvaluateAsync({definition.ContextType} ctx, FactBag facts, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        foreach (string line in localFunction)
        {
            sb.AppendLine($"            {line}");
        }

        sb.AppendLine();
        foreach (string line in invokeLogic)
        {
            sb.AppendLine($"            {line}");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            return RuleResult.Failure(ex.Message);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public Task ExecuteAsync({definition.ContextType} context, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Task.CompletedTask;");
        sb.AppendLine("    }");

        foreach (string line in helperMethods)
        {
            sb.AppendLine(line);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static (string Fields, string Constructor) RenderDependencyConstructor(string className, IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return (string.Empty, string.Empty);
        }

        string fields = string.Join("\n",
            dependencies.Select(d => $"    private readonly {d.TypeName} {d.FieldName};"));

        string args = string.Join(", ", dependencies.Select(d => $"{d.TypeName} {d.ConstructorParameterName}"));
        string assigns = string.Join("\n",
            dependencies.Select(d => $"        {d.FieldName} = {d.ConstructorParameterName};"));

        string ctor = "    public " + className + "(" + args + ")" + "\n"
            + "    {" + "\n"
            + assigns + "\n"
            + "    }";

        return (fields, ctor);
    }

    private static string[] RenderHelperMethods(IReadOnlyList<HelperMethodDefinition> helpers)
    {
        if (helpers.Count == 0)
        {
            return Array.Empty<string>();
        }

        List<string> lines = [];

        foreach (HelperMethodDefinition helper in helpers)
        {
            lines.Add(string.Empty);
            string asyncModifier = helper.IsAsync ? "async " : string.Empty;
            string parameters = string.Join(", ", helper.Parameters.Select(RenderParameter));
            lines.Add($"    private static {asyncModifier}{helper.ReturnType} {helper.MethodName}({parameters})");
            lines.Add("    {");

            if (!string.IsNullOrWhiteSpace(helper.MethodBody))
            {
                string[] bodyLines = GetBlockBodyLines(helper.MethodBody!);
                foreach (string line in bodyLines)
                {
                    lines.Add($"        {line}");
                }
            }
            else if (!string.IsNullOrWhiteSpace(helper.ExpressionBody))
            {
                lines.Add($"        return {helper.ExpressionBody};");
            }
            else
            {
                lines.Add("        return default!;");
            }

            lines.Add("    }");
        }

        return lines.ToArray();
    }

    private static string[] RenderLocalFunction(ExtractedRuleDefinition definition)
    {
        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string parameterList = string.Join(", ", definition.Parameters.Select(RenderParameter));
        string asyncModifier = definition.IsAsync ? "async " : string.Empty;
        string returnType = definition.ReturnType;

        List<string> lines =
        [
            $"{asyncModifier}{returnType} {localName}({parameterList})",
            "{"
        ];

        if (!string.IsNullOrWhiteSpace(definition.MethodBody))
        {
            string[] bodyLines = GetBlockBodyLines(definition.MethodBody!);
            foreach (string line in bodyLines)
            {
                lines.Add($"    {line}");
            }
        }
        else if (!string.IsNullOrWhiteSpace(definition.ExpressionBody))
        {
            lines.Add($"    return {definition.ExpressionBody};");
        }
        else
        {
            lines.Add("    return default!;");
        }

        lines.Add("}");
        return lines.ToArray();
    }

    private static string[] RenderInvokeLogic(ExtractedRuleDefinition definition)
    {
        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string args = string.Join(", ", definition.Parameters.Select(p => MapInvocationArgument(p, definition.ContextType)));
        string returnType = definition.ReturnType.Replace(" ", string.Empty);

        if (returnType == "Task<RuleResult>")
        {
            return new[] { $"var __result = await {localName}({args});", "return __result;" };
        }

        if (returnType == "RuleResult")
        {
            return new[] { $"var __result = {localName}({args});", "return __result;" };
        }

        if (returnType == "Task<bool>")
        {
            return new[] { $"var __ok = await {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");" };
        }

        if (returnType == "bool")
        {
            return new[] { $"var __ok = {localName}({args});", "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");" };
        }

        if (returnType == "Task")
        {
            return new[] { $"await {localName}({args});", "return RuleResult.Passed();" };
        }

        if (returnType == "void")
        {
            return new[] { $"{localName}({args});", "return RuleResult.Passed();" };
        }

        if (returnType.StartsWith("Task<"))
        {
            return new[]
            {
                $"var __value = await {localName}({args});",
                $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
                "return RuleResult.Passed();"
            };
        }

        return new[]
        {
            $"var __value = {localName}({args});",
            $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
            "return RuleResult.Passed();"
        };
    }

    private static string RenderDependenciesProperty(IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return "Array.Empty<System.Type>()";
        }

        string types = string.Join(", ", dependencies.Select(d => $"typeof({d.TypeName})"));
        return $"new[] {{ {types} }}";
    }

    private static string MapInvocationArgument(ParameterModel parameter, string contextType)
    {
        string typeName = parameter.TypeName.Replace(" ", string.Empty);
        if (typeName is "FactBag" or "Muonroi.RuleEngine.Abstractions.FactBag")
        {
            return "facts";
        }

        if (typeName is "CancellationToken" or "System.Threading.CancellationToken")
        {
            return "ct";
        }

        if (string.Equals(typeName, contextType.Replace(" ", string.Empty), StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "ctx", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "context", StringComparison.OrdinalIgnoreCase))
        {
            return "ctx";
        }

        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return parameter.DefaultValueExpression!;
        }

        return "default!";
    }

    private static string RenderParameter(ParameterModel p)
    {
        if (p.HasDefaultValue && !string.IsNullOrWhiteSpace(p.DefaultValueExpression))
        {
            return $"{p.TypeName} {p.Name} = {p.DefaultValueExpression}";
        }

        return $"{p.TypeName} {p.Name}";
    }

    private static string ToIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "GeneratedRule";
        }

        char[] chars = value.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_').ToArray();
        string normalized = new(chars);
        if (!char.IsLetter(normalized[0]) && normalized[0] != '_')
        {
            normalized = "R_" + normalized;
        }

        return normalized;
    }

    private static string Escape(string text)
    {
        return text
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    private static string[] GetBlockBodyLines(string bodyText)
    {
        if (string.IsNullOrWhiteSpace(bodyText))
        {
            return Array.Empty<string>();
        }

        string normalized = bodyText.Trim();
        if (normalized.StartsWith("{", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(1);
        }

        if (normalized.EndsWith("}", StringComparison.Ordinal))
        {
            normalized = normalized.Substring(0, normalized.Length - 1);
        }

        return normalized
            .Split(new[] { "\r\n", "\n" }, StringSplitOptions.None)
            .Select(x => x.TrimEnd())
            .Where(x => x.Length > 0)
            .ToArray();
    }
}
