namespace Muonroi.RuleEngine.SourceGenerators.SourceWriters;

internal static class RuleAuthoringManifestSourceWriter
{
    public static string Render(string rootNamespace, AuthoringManifestDefinition manifest)
    {
        List<string> lines =
        [
            "// <auto-generated/>",
            "#nullable enable",
            "namespace " + rootNamespace + ".Generated;",
            "",
            "internal static class RuleCatalogRegistration",
            "{",
            "    public static global::Muonroi.RuleEngine.Abstractions.Authoring.IRuleAuthoringManifestProvider GetManifestProvider()",
            "    {",
            "        return new GeneratedManifestProvider();",
            "    }",
            "}",
            "",
            "internal sealed class GeneratedManifestProvider : global::Muonroi.RuleEngine.Abstractions.Authoring.IRuleAuthoringManifestProvider",
            "{",
            "    public global::Muonroi.RuleEngine.Abstractions.Authoring.MRuleAuthoringManifest GetManifest()",
            "    {",
            "        return " + RenderManifest(manifest, 2) + ";",
            "    }",
            "}"
        ];

        return string.Join("\n", lines);
    }

    private static string RenderManifest(AuthoringManifestDefinition manifest, int indentLevel)
    {
        string indent = Indent(indentLevel);
        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MRuleAuthoringManifest",
            indent + "{",
            indent + "    AssemblyName = " + Quote(manifest.AssemblyName) + ",",
            indent + "    AssemblyVersion = " + Quote(manifest.AssemblyVersion) + ",",
            indent + "    Rules = new global::Muonroi.RuleEngine.Abstractions.Authoring.MRuleAuthoringEntry[]",
            indent + "    {"
        ];

        foreach (AuthoringRuleDefinition rule in manifest.Rules)
        {
            lines.Add(indent + "        " + RenderRule(rule, indentLevel + 2) + ",");
        }

        lines.Add(indent + "    }");
        lines.Add(indent + "}");
        return string.Join("\n", lines);
    }

    private static string RenderRule(AuthoringRuleDefinition rule, int indentLevel)
    {
        string indent = Indent(indentLevel);
        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MRuleAuthoringEntry",
            indent + "{",
            indent + "    Code = " + Quote(rule.Code) + ",",
            indent + "    Order = " + rule.Order + ",",
            indent + "    DependsOn = " + RenderStringArray(rule.DependsOn) + ",",
            indent + "    ContextTypeName = " + QuoteOrNull(rule.ContextTypeName) + ",",
            indent + "    ContextTitle = " + QuoteOrNull(rule.ContextTitle) + ",",
            indent + "    ContextDescription = " + QuoteOrNull(rule.ContextDescription) + ",",
            indent + "    ContextSchema = " + RenderSchemaNode(rule.ContextSchema, indentLevel + 1) + ",",
            indent + "    ConsumedFacts = " + RenderFactArray(rule.ConsumedFacts, indentLevel + 1) + ",",
            indent + "    ProducedFacts = " + RenderFactArray(rule.ProducedFacts, indentLevel + 1) + ",",
            indent + "    DisplayName = " + QuoteOrNull(rule.DisplayName) + ",",
            indent + "    Category = " + QuoteOrNull(rule.Category) + ",",
            indent + "    Icon = " + QuoteOrNull(rule.Icon) + ",",
            indent + "    Tags = " + RenderStringArray(rule.Tags) + ",",
            indent + "    Description = " + QuoteOrNull(rule.Description) + ",",
            indent + "    IsPaletteVisible = " + (rule.IsPaletteVisible ? "true" : "false"),
            indent + "}"
        ];
        return string.Join("\n", lines);
    }

    private static string RenderFactArray(IReadOnlyList<AuthoringFactDefinition> facts, int indentLevel)
    {
        string indent = Indent(indentLevel);
        if (facts.Count == 0)
        {
            return "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactEntry[0]";
        }

        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactEntry[]",
            indent + "{"
        ];
        foreach (AuthoringFactDefinition fact in facts)
        {
            lines.Add(indent + "    " + RenderFact(fact, indentLevel + 2) + ",");
        }
        lines.Add(indent + "}");
        return string.Join("\n", lines);
    }

    private static string RenderFact(AuthoringFactDefinition fact, int indentLevel)
    {
        string indent = Indent(indentLevel);
        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactEntry",
            indent + "{",
            indent + "    Key = " + Quote(fact.Key) + ",",
            indent + "    Label = " + QuoteOrNull(fact.Label) + ",",
            indent + "    ClrTypeName = " + QuoteOrNull(fact.ClrTypeName) + ",",
            indent + "    Description = " + QuoteOrNull(fact.Description) + ",",
            indent + "    Example = " + QuoteOrNull(fact.Example) + ",",
            indent + "    Schema = " + RenderSchemaNode(fact.Schema, indentLevel + 1),
            indent + "}"
        ];
        return string.Join("\n", lines);
    }

    private static string RenderSchemaNode(AuthoringSchemaNode? schema, int indentLevel)
    {
        if (schema is null)
        {
            return "null";
        }

        string indent = Indent(indentLevel);
        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactSchemaNode",
            indent + "{",
            indent + "    TypeName = " + Quote(schema.TypeName) + ",",
            indent + "    IsNullable = " + (schema.IsNullable ? "true" : "false") + ",",
            indent + "    Description = " + QuoteOrNull(schema.Description) + ",",
            indent + "    Fields = " + RenderFieldArray(schema.Fields, indentLevel + 1),
            indent + "}"
        ];
        return string.Join("\n", lines);
    }

    private static string RenderFieldArray(IReadOnlyList<AuthoringSchemaField> fields, int indentLevel)
    {
        string indent = Indent(indentLevel);
        if (fields.Count == 0)
        {
            return "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactSchemaField[0]";
        }

        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactSchemaField[]",
            indent + "{"
        ];
        foreach (AuthoringSchemaField field in fields)
        {
            lines.Add(indent + "    " + RenderField(field, indentLevel + 2) + ",");
        }
        lines.Add(indent + "}");
        return string.Join("\n", lines);
    }

    private static string RenderField(AuthoringSchemaField field, int indentLevel)
    {
        string indent = Indent(indentLevel);
        List<string> lines =
        [
            "new global::Muonroi.RuleEngine.Abstractions.Authoring.MFactSchemaField",
            indent + "{",
            indent + "    Path = " + Quote(field.Path) + ",",
            indent + "    Label = " + Quote(field.Label) + ",",
            indent + "    DataType = " + Quote(field.DataType) + ",",
            indent + "    Required = " + (field.Required ? "true" : "false") + ",",
            indent + "    Description = " + QuoteOrNull(field.Description) + ",",
            indent + "    Example = " + QuoteOrNull(field.Example) + ",",
            indent + "    Children = " + RenderFieldArray(field.Children, indentLevel + 1),
            indent + "}"
        ];
        return string.Join("\n", lines);
    }

    private static string RenderStringArray(IReadOnlyList<string> values)
    {
        if (values.Count == 0)
        {
            return "new string[0]";
        }

        return "new string[] { " + string.Join(", ", values.Select(Quote)) + " }";
    }

    private static string Quote(string value)
    {
        return "@\"" + value.Replace("\"", "\"\"") + "\"";
    }

    private static string QuoteOrNull(string? value)
    {
        return value is null ? "null" : Quote(value);
    }

    private static string Indent(int level)
    {
        return new string(' ', level * 4);
    }
}
