using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace Muonroi.Tenancy.SiteProfile.SourceGenerators;

/// <summary>
/// Analyzer MSP002 — warns when a non-generated ISiteProfile class is missing a keyed DI registration
/// for a service type registered via AddSiteResolvedService&lt;T&gt;().
///
/// Rationale: At 20+ sites scale, manually verifying that every ISiteProfile.RegisterServices() call
/// contains the correct AddKeyedScoped/AddKeyedSingleton/AddKeyedTransient for every shared service
/// type is error-prone. MSP002 enforces this contract at compile time.
///
/// Skip rule: classes decorated with [GenerateSiteProfile] are excluded — those sites use
/// RegisterAdditionalServices partial method (generated by 38-02) for consumer-specific keyed DI.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ContractComplianceAnalyzer : DiagnosticAnalyzer
{
    /// <summary>MSP002 diagnostic identifier.</summary>
    public const string DiagnosticId = "MSP002";

    private static readonly DiagnosticDescriptor Rule = new(
        id: DiagnosticId,
        title: "Site missing keyed service registration",
        messageFormat: "Site '{0}' does not register keyed service for '{1}'. Add services.AddKeyedScoped<{1}, {2}>(\"{0}\") in RegisterServices().",
        category: "Muonroi.SiteProfile",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "Each ISiteProfile.RegisterServices() must call AddKeyedScoped/AddKeyedSingleton/AddKeyedTransient for every service type registered via AddSiteResolvedService<T>().");

    /// <inheritdoc/>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(Rule);

    /// <inheritdoc/>
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        // Use CompilationStartAction to resolve type symbols once per compilation (RS1030 compliant).
        context.RegisterCompilationStartAction(compilationContext =>
        {
            var iSiteProfile = compilationContext.Compilation
                .GetTypeByMetadataName("Muonroi.Tenancy.SiteProfile.ISiteProfile");

            // If ISiteProfile is not referenced, nothing to analyze
            if (iSiteProfile is null) return;

            // Resolve [GenerateSiteProfile] attribute type — may be null if attribute not yet generated
            var generateSiteProfileAttribute = compilationContext.Compilation
                .GetTypeByMetadataName("Muonroi.Tenancy.SiteProfile.GenerateSiteProfileAttribute");

            // Thread-safe collections for accumulation across concurrent SemanticModelAction callbacks.
            // Key: fully-qualified service interface name, Value: true (set semantics via dictionary)
            var siteResolvedServiceTypes = new ConcurrentDictionary<string, bool>(System.StringComparer.Ordinal);

            // Key: class symbol (EquatableSymbol wrapper not available in netstandard2.0, use SymbolId string)
            // Value: (siteId, set of keyed service type names registered by this class, class location)
            var profileData = new ConcurrentDictionary<string, ProfileRegistrationData>(System.StringComparer.Ordinal);

            // Collect all ISiteProfile implementations and AddSiteResolvedService<T> calls
            compilationContext.RegisterSemanticModelAction(semanticModelContext =>
            {
                var model = semanticModelContext.SemanticModel;
                var root = model.SyntaxTree.GetRoot();

                // 1. Collect ISiteProfile implementations
                foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
                {
                    if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                        continue;

                    if (symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface)
                        continue;

                    if (!symbol.AllInterfaces.Any(i =>
                        SymbolEqualityComparer.Default.Equals(i, iSiteProfile)))
                        continue;

                    // Extract SiteId string value (same pattern as SiteIdLiteralAnalyzer)
                    string? siteIdValue = ExtractSiteIdLiteralValue(symbol);
                    if (siteIdValue is null) continue;

                    // Skip classes decorated with [GenerateSiteProfile] — those use partial RegisterAdditionalServices
                    bool hasGenerateAttr = generateSiteProfileAttribute is not null
                        && symbol.GetAttributes().Any(a =>
                            SymbolEqualityComparer.Default.Equals(a.AttributeClass, generateSiteProfileAttribute));

                    if (hasGenerateAttr) continue;

                    // Walk RegisterServices() method body to find AddKeyed* calls
                    var registeredKeyedTypes = new ConcurrentDictionary<string, bool>(System.StringComparer.Ordinal);
                    var registerServicesMethod = classDecl.Members
                        .OfType<MethodDeclarationSyntax>()
                        .FirstOrDefault(m => m.Identifier.ValueText == "RegisterServices");

                    if (registerServicesMethod is not null)
                    {
                        foreach (var invocation in registerServicesMethod.DescendantNodes()
                            .OfType<InvocationExpressionSyntax>())
                        {
                            if (model.GetSymbolInfo(invocation).Symbol is not IMethodSymbol methodSymbol)
                                continue;

                            // Match AddKeyedScoped, AddKeyedSingleton, AddKeyedTransient
                            if (!methodSymbol.Name.StartsWith("AddKeyed", System.StringComparison.Ordinal))
                                continue;

                            // Service type is TypeArguments[0]
                            if (methodSymbol.TypeArguments.Length >= 1)
                            {
                                var serviceTypeName = methodSymbol.TypeArguments[0].ToDisplayString(
                                    SymbolDisplayFormat.FullyQualifiedFormat);
                                registeredKeyedTypes.TryAdd(serviceTypeName, true);
                            }
                        }
                    }

                    // Use fully-qualified class name as key for deduplication across partial classes
                    string classKey = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var location = classDecl.Identifier.GetLocation();

                    profileData.AddOrUpdate(classKey,
                        new ProfileRegistrationData(siteIdValue, registeredKeyedTypes, location),
                        (_, existing) =>
                        {
                            // Merge keyed types if class appears in multiple partials
                            foreach (var kv in registeredKeyedTypes)
                                existing.RegisteredKeyedServiceTypes.TryAdd(kv.Key, true);
                            return existing;
                        });
                }

                // 2. Collect AddSiteResolvedService<T> invocations
                foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
                {
                    if (model.GetSymbolInfo(invocation).Symbol is not IMethodSymbol methodSymbol)
                        continue;

                    if (!methodSymbol.Name.Equals("AddSiteResolvedService", System.StringComparison.Ordinal))
                        continue;

                    // Service type is TypeArguments[0]
                    if (methodSymbol.TypeArguments.Length >= 1)
                    {
                        var serviceTypeName = methodSymbol.TypeArguments[0].ToDisplayString(
                            SymbolDisplayFormat.FullyQualifiedFormat);
                        siteResolvedServiceTypes.TryAdd(serviceTypeName, true);
                    }
                }
            });

            // End of compilation: cross-reference profiles vs required service types
            compilationContext.RegisterCompilationEndAction(compilationEndContext =>
            {
                if (siteResolvedServiceTypes.IsEmpty) return;

                foreach (var profileEntry in profileData.Values)
                {
                    foreach (var requiredService in siteResolvedServiceTypes.Keys)
                    {
                        if (profileEntry.RegisteredKeyedServiceTypes.ContainsKey(requiredService))
                            continue;

                        // Build suggested implementation name: {SiteId}{InterfaceName}
                        // Strip leading 'I' from interface name for suggestion
                        string interfaceShortName = GetShortName(requiredService);
                        string siteIdPascal = ToPascalCase(profileEntry.SiteId);
                        string suggestedImpl = siteIdPascal + StripLeadingI(interfaceShortName);

                        compilationEndContext.ReportDiagnostic(
                            Diagnostic.Create(
                                Rule,
                                profileEntry.ClassLocation,
                                profileEntry.SiteId,
                                interfaceShortName,
                                suggestedImpl));
                    }
                }
            });
        });
    }

    /// <summary>
    /// Extracts the compile-time SiteId string value from an ISiteProfile implementation.
    /// Handles arrow expression, auto-property initializer, and simple return statement patterns.
    /// (Shared pattern with SiteIdLiteralAnalyzer.)
    /// </summary>
    private static string? ExtractSiteIdLiteralValue(INamedTypeSymbol profileSymbol)
    {
        var siteIdProp = profileSymbol.GetMembers("SiteId")
            .OfType<IPropertySymbol>()
            .FirstOrDefault();
        if (siteIdProp is null) return null;

        foreach (var syntaxRef in siteIdProp.DeclaringSyntaxReferences)
        {
            var syntax = syntaxRef.GetSyntax();
            if (syntax is not PropertyDeclarationSyntax propDecl) continue;

            // Arrow expression: string SiteId => "VALUE"
            if (propDecl.ExpressionBody?.Expression is LiteralExpressionSyntax arrowLiteral)
                return arrowLiteral.Token.ValueText;

            // Auto-property with initializer: string SiteId { get; } = "VALUE"
            if (propDecl.Initializer?.Value is LiteralExpressionSyntax initLiteral)
                return initLiteral.Token.ValueText;

            // Getter with return statement: string SiteId { get { return "VALUE"; } }
            var getter = propDecl.AccessorList?.Accessors
                .FirstOrDefault(a => a.Keyword.ValueText == "get");
            if (getter?.Body?.Statements.FirstOrDefault() is ReturnStatementSyntax ret
                && ret.Expression is LiteralExpressionSyntax retLiteral)
                return retLiteral.Token.ValueText;
        }

        return null;
    }

    /// <summary>Gets the short (unqualified) type name from a fully-qualified name.</summary>
    private static string GetShortName(string fullyQualifiedName)
    {
        int lastDot = fullyQualifiedName.LastIndexOf('.');
        string raw = lastDot >= 0 ? fullyQualifiedName.Substring(lastDot + 1) : fullyQualifiedName;
        // Strip "global::" prefix if present
        const string globalPrefix = "global::";
        if (raw.StartsWith(globalPrefix, System.StringComparison.Ordinal))
            raw = raw.Substring(globalPrefix.Length);
        return raw;
    }

    /// <summary>Strips a leading 'I' from an interface name (e.g., IMyService -> MyService).</summary>
    private static string StripLeadingI(string name)
    {
        if (name.Length > 1 && name[0] == 'I' && char.IsUpper(name[1]))
            return name.Substring(1);
        return name;
    }

    /// <summary>Converts a siteId to PascalCase (e.g., "tci" -> "Tci", "site-01" -> "Site01").</summary>
    private static string ToPascalCase(string siteId)
    {
        if (string.IsNullOrEmpty(siteId)) return siteId;
        var sb = new System.Text.StringBuilder(siteId.Length);
        bool capitalizeNext = true;
        foreach (char c in siteId)
        {
            if (!char.IsLetterOrDigit(c))
            {
                capitalizeNext = true;
                continue;
            }
            sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
            capitalizeNext = false;
        }
        return sb.ToString();
    }

    /// <summary>Data accumulated per ISiteProfile class during SemanticModelAction callbacks.</summary>
    private sealed class ProfileRegistrationData
    {
        public string SiteId { get; }
        public ConcurrentDictionary<string, bool> RegisteredKeyedServiceTypes { get; }
        public Location ClassLocation { get; }

        public ProfileRegistrationData(
            string siteId,
            ConcurrentDictionary<string, bool> registeredKeyedServiceTypes,
            Location classLocation)
        {
            SiteId = siteId;
            RegisteredKeyedServiceTypes = registeredKeyedServiceTypes;
            ClassLocation = classLocation;
        }
    }
}
