global using Grpc.Core;
global using Grpc.Core.Interceptors;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.DependencyInjection;
global using Muonroi.Tenancy.SiteProfile;
global using System.Reflection;
global using System.Collections.Concurrent;
global using GrpcClientFactory = Grpc.Net.ClientFactory.GrpcClientFactory;
global using Microsoft.Extensions.Options;
global using Muonroi.Core.Abstractions.Guards;
global using System.Diagnostics.CodeAnalysis;
global using Muonroi.Core.Abstractions.Exceptions;
global using System.Runtime.CompilerServices;
global using Microsoft.Extensions.Logging;
global using Muonroi.Logging.Abstractions;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Routing;
