namespace Muonroi.Tenancy.SiteProfile.Grpc;

/// <summary>
/// Resolves the correct gRPC client for the current site at runtime.
/// Consumers inject this interface instead of writing if/switch on SiteCode.
///
/// <example>
/// <code>
/// // Resolve raw client for current site:
/// var client = factory.CreateForCurrentSite&lt;FcdService.FcdServiceClient&gt;("fcd");
/// var response = await client.CreateAsync(request);
///
/// // Resolve unified facade for current site:
/// var facade = factory.CreateFacadeForCurrentSite&lt;ITciFcdClient&gt;("fcd");
/// var result = await facade.CreateV4Async(request);
/// </code>
/// </example>
/// </summary>
public interface ISiteGrpcClientFactory
{
    /// <summary>
    /// Creates the gRPC client registered for the current site.
    /// Falls back to the "default" registration when no site-specific client is found.
    /// </summary>
    /// <typeparam name="TBase">The gRPC client base type (e.g., FcdService.FcdServiceClient).</typeparam>
    /// <param name="serviceName">The named service key used during AddSiteGrpcClient registration.</param>
    /// <returns>The site-specific (or default) gRPC client instance.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when neither a site-specific nor a default client is registered for <paramref name="serviceName"/>.
    /// </exception>
    TBase CreateForCurrentSite<TBase>(string serviceName) where TBase : ClientBase;

    /// <summary>
    /// Creates the unified facade client for the current site.
    /// The facade wraps shared + per-site gRPC clients behind one interface
    /// (generated by [GenerateSiteGrpcFacade] and registered via AddSiteGrpcFacadeClient).
    /// Falls back to the "default" registration when no site-specific facade is found.
    /// </summary>
    /// <typeparam name="TFacade">The facade interface type (e.g., ITciFcdClient).</typeparam>
    /// <param name="serviceName">The named service key used during AddSiteGrpcFacadeClient registration.</param>
    /// <returns>The site-specific (or default) facade client instance.</returns>
    /// <exception cref="InvalidOperationException">
    /// Thrown when neither a site-specific nor a default facade is registered for <paramref name="serviceName"/>.
    /// </exception>
    TFacade CreateFacadeForCurrentSite<TFacade>(string serviceName) where TFacade : class;
}
