apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "worker.fullname" . }}-np
spec:
  podSelector:
    matchLabels:
      app: {{ include "worker.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
