<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Muonroi.Tenancy.SiteProfile" />
    <PackageReference Include="Muonroi.Tenancy.SiteProfile.SourceGenerators" />
    <PackageReference Include="Muonroi.Tenancy.SiteProfile.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TestProject.Service.Core\TestProject.Service.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
