WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

// Register Rule Engine
builder.Services.AddMRuleEngine<ValidationContext>(options => 
{
    options.ExecutionMode = ExecutionMode.AllOrNothing;
});

// Register rules generated by the Source Generator
builder.Services.AddMGeneratedRules();

// --- Standard wiring ---
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new()
    {
        Title = "Quickstart.RuleEngine.SourceGenerators API",
        Version = "v1",
        Description = "Demonstrates Source Generators for Rules."
    });
});

WebApplication app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI();

app.MapPost("/api/validate", async (ValidationContext context, RuleOrchestrator<ValidationContext> orchestrator, CancellationToken ct) =>
{
    var result = await orchestrator.ExecuteAsync(context, HookPoint.BeforeRule, ct);
    
    if (!result.Success)
    {
        return Results.BadRequest(result.Errors);
    }
    
    return Results.Ok(new 
    {
        Status = "Valid",
        IsAdult = result.Facts.Get<bool>("IsAdult")
    });
});

app.MapGet("/health", () => Results.Ok(new { status = "Healthy" }));
app.Run();
