<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsMuonroiTestProject>false</IsMuonroiTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <!-- Use ProjectReference with OutputItemType="Analyzer" to enable the source generator -->
    <ProjectReference Include="../../../../src/Muonroi.Diagnostics.Generator/Muonroi.Diagnostics.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
