<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
    <DeployExtension>false</DeployExtension>
    <NoWarn>$(NoWarn);VSTHRD010;VSTHRD101;VSTHRD109;VSSDK006</NoWarn>
    <CreatePkgDefAssemblyToProcess>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll</CreatePkgDefAssemblyToProcess>
    <TargetVsixContainerName>Muonroi.RuleGen.VisualStudio.vsix</TargetVsixContainerName>
    <TargetVsixContainer>$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetVsixContainerName)</TargetVsixContainer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.IO.Redist" Version="6.1.3" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.10.40171" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.10.2185" PrivateAssets="all" />
    <PackageReference Include="MimeKit" Version="4.15.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Design" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="RuleGenCommands.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
    <EmbeddedResource Update="VSPackage.resx">
      <MergeWithCTO>true</MergeWithCTO>
      <ManifestResourceName>VSPackage</ManifestResourceName>
    </EmbeddedResource>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>

  <Import Project="$(VSToolsPath)\\VSSDK\\Microsoft.VsSDK.targets" Condition="Exists('$(VSToolsPath)\\VSSDK\\Microsoft.VsSDK.targets')" />
</Project>
