using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Muonroi.RuleEngine.SourceGenerators;

/// <summary>
/// Incremental generator that registers discovered rule implementations.
/// </summary>
[Generator]
public sealed class RuleRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Quét các class kế thừa IRule<T> hoặc được sinh ra bởi generator của chúng ta
        IncrementalValuesProvider<INamedTypeSymbol> ruleClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetRuleClassSymbol(ctx))
            .Where(static s => s is not null)!;

        // 2. Gom nhóm theo ContextType
        IncrementalValueProvider<ImmutableArray<INamedTypeSymbol>> collectedRules = ruleClasses.Collect();

        // 3. Sinh source đăng ký
        context.RegisterSourceOutput(collectedRules, static (spc, rules) => Execute(rules, spc));
    }

    private static INamedTypeSymbol? GetRuleClassSymbol(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (symbol == null) return null;

        if (symbol.AllInterfaces.Any(i => i.Name == "IRule" && i.IsGenericType))
        {
            return symbol;
        }

        return null;
    }

    private static void Execute(ImmutableArray<INamedTypeSymbol> rules, SourceProductionContext context)
    {
        if (rules.IsDefaultOrEmpty) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Muonroi.RuleEngine.Abstractions;");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace Muonroi.RuleEngine.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class RuleEngineRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedRules(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var rule in rules.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
        {
            string fullName = rule.ToDisplayString();
            sb.AppendLine($"        services.AddTransient<IRule<{GetContextType(rule)}>, {fullName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("RuleEngineRegistrationExtensions.g.cs", sb.ToString());
    }

    private static string GetContextType(INamedTypeSymbol ruleSymbol)
    {
        var ruleInterface = ruleSymbol.AllInterfaces.FirstOrDefault(i => i.Name == "IRule" && i.IsGenericType);
        if (ruleInterface != null && ruleInterface.TypeArguments.Length > 0)
        {
            return ruleInterface.TypeArguments[0].ToDisplayString();
        }
        return "object";
    }
}
