global using ExcelDataReader;
global using Muonroi.Logging.Abstractions;
global using Muonroi.RuleEngine.Abstractions;
global using Muonroi.RuleEngine.DecisionTable.Models;
global using System.Collections.Concurrent;
global using System.Globalization;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Xml.Linq;
global using DecisionTableModel = Muonroi.RuleEngine.DecisionTable.Models.DecisionTable;
