<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
<PackageReference Include="MailKit" />
<PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <ProjectReference Include="../../src/Muonroi.RuleEngine.Core/Muonroi.RuleEngine.Core.csproj" />
    <ProjectReference Include="../../src/Muonroi.RuleEngine.Testing/Muonroi.RuleEngine.Testing.csproj" />
</ItemGroup>
</Project>


