<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="MimeKit" />
    <PackageReference Include="Scriban" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\tools\Muonroi.RuleGen\Muonroi.RuleGen.csproj" />
  </ItemGroup>
</Project>
