using Muonroi.RuleGen.Models;
using Muonroi.RuleGen.Writers;
using FluentAssertions;
using Xunit;

namespace Muonroi.RuleGen.Tests;

public class RegistrationWriterTests
{
    [Fact]
    public void Render_WithRules_GeneratesRegistration()
    {
        List<DiscoveredRuleType> discovered =
        [
            new("MyApp.Rules.ValidateOrderRule", "OrderContext"),
            new("MyApp.Rules.CheckInventoryRule", "OrderContext")
        ];

        string result = RegistrationWriter.Render(
            "MyApp.Rules",
            discovered,
            [],
            includeRuleEngineRegistration: true,
            "MGeneratedRuleRegistrationExtensions");

        result.Should().Contain("// <auto-generated />");
        result.Should().Contain("namespace MyApp.Rules;");
        result.Should().Contain("public static class MGeneratedRuleRegistrationExtensions");
        result.Should().Contain("AddMGeneratedRules");
        result.Should().Contain("AddRuleEngine<OrderContext>");
        result.Should().Contain("ValidateOrderRule");
        result.Should().Contain("CheckInventoryRule");
    }

    [Fact]
    public void Render_WithoutRuleEngineRegistration_OmitsAddRuleEngine()
    {
        List<DiscoveredRuleType> discovered = [new("RuleA", "CtxA")];

        string result = RegistrationWriter.Render(
            "TestNs",
            discovered,
            [],
            includeRuleEngineRegistration: false,
            "MyExtensions");

        result.Should().NotContain("AddRuleEngine");
        result.Should().NotContain("using Muonroi.RuleEngine.Core;");
    }

    [Fact]
    public void Render_WithDispatchers_RegistersDispatchers()
    {
        List<DiscoveredDispatcherContext> dispatchers =
        [
            new("OrderContext", "IOrderDispatcher", "OrderDispatcher", "OrderDispatcher.g.cs")
        ];

        string result = RegistrationWriter.Render(
            "TestNs",
            [],
            dispatchers,
            includeRuleEngineRegistration: false,
            "MyExtensions");

        result.Should().Contain("TryAddScoped<IOrderDispatcher, OrderDispatcher>");
    }

    [Fact]
    public void Render_EmptyClassName_UsesDefault()
    {
        string result = RegistrationWriter.Render("TestNs", [], [], false, "");
        result.Should().Contain("class MGeneratedRuleRegistrationExtensions");
    }

    [Fact]
    public void Render_ClassNameStartsWithDigit_Prefixed()
    {
        string result = RegistrationWriter.Render("TestNs", [], [], false, "1Extensions");
        result.Should().Contain("class _1Extensions");
    }

    [Fact]
    public void Render_ClassNameWithSpecialChars_Sanitized()
    {
        string result = RegistrationWriter.Render("TestNs", [], [], false, "My-Extensions.Test");
        result.Should().Contain("class My_Extensions_Test");
    }

    [Fact]
    public void Render_MultipleContextTypes_RegistersAll()
    {
        List<DiscoveredRuleType> discovered =
        [
            new("RuleA", "ContextA"),
            new("RuleB", "ContextB")
        ];

        string result = RegistrationWriter.Render("TestNs", discovered, [], true, "Ext");

        result.Should().Contain("AddRuleEngine<ContextA>");
        result.Should().Contain("AddRuleEngine<ContextB>");
    }
}
