using Muonroi.RuleGen.Models;
using Muonroi.RuleGen.Writers;
using FluentAssertions;
using Xunit;

namespace Muonroi.RuleGen.Tests;

public class RuleClassWriterTests
{
    private static ExtractedRuleDefinition CreateDefinition(
        string code = "TEST_001",
        string methodName = "DoSomething",
        string returnType = "Task<RuleResult>",
        bool isAsync = true,
        bool useFactBagAware = false,
        IReadOnlyList<string>? dependsOn = null,
        IReadOnlyList<ServiceDependency>? dependencies = null,
        string? documentationComment = null,
        string? methodBody = null,
        string? expressionBody = null)
    {
        return new ExtractedRuleDefinition(
            Code: code,
            MethodName: methodName,
            ClassName: "TestHandler",
            SourceNamespace: "Test",
            OutputNamespace: "Test.Rules",
            ContextType: "TestContext",
            ReturnType: returnType,
            Order: 10,
            HookPoint: "BeforeRule",
            DependsOn: dependsOn ?? [],
            Usings: ["System.Linq"],
            CustomAttributes: [],
            Parameters: [new ParameterModel("ctx", "TestContext", false, null)],
            Dependencies: dependencies ?? [],
            HelperMethods: [],
            DocumentationComment: documentationComment,
            MethodBody: methodBody ?? "return Task.FromResult(RuleResult.Passed());",
            ExpressionBody: expressionBody,
            IsAsync: isAsync,
            SourceFile: "TestHandler.cs",
            SourceLine: 42,
            UseFactBagAware: useFactBagAware);
    }

    [Fact]
    public void Render_BasicRule_ContainsAutoGenComment()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("// <auto-generated />");
    }

    [Fact]
    public void Render_BasicRule_ContainsNamespace()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("namespace Test.Rules;");
    }

    [Fact]
    public void Render_BasicRule_GeneratesClassName()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("class TEST_001Rule");
    }

    [Fact]
    public void Render_BasicRule_ImplementsIRule()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("IRule<TestContext>");
    }

    [Fact]
    public void Render_FactBagAware_InheritsMFactBagAwareRule()
    {
        string result = RuleClassWriter.Render(CreateDefinition(useFactBagAware: true), null, null, null);
        result.Should().Contain("MFactBagAwareRule<TestContext>");
    }

    [Fact]
    public void Render_WithAuthor_IncludesAuthorComment()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, "john", null);
        result.Should().Contain("// Author: john");
    }

    [Fact]
    public void Render_WithGitCommit_IncludesCommitComment()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, "abc123");
        result.Should().Contain("// Commit: abc123");
    }

    [Fact]
    public void Render_WithTenant_IncludesTenantComment()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), "tenant-1", null, null);
        result.Should().Contain("// Tenant: tenant-1");
    }

    [Fact]
    public void Render_WithDependsOn_IncludesDependencies()
    {
        var def = CreateDefinition(dependsOn: ["RULE_A", "RULE_B"]);
        string result = RuleClassWriter.Render(def, null, null, null);
        result.Should().Contain("\"RULE_A\"");
        result.Should().Contain("\"RULE_B\"");
    }

    [Fact]
    public void Render_NoDependencies_EmptyArray()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("Array.Empty<string>()");
    }

    [Fact]
    public void Render_WithServiceDependency_GeneratesConstructor()
    {
        var deps = new List<ServiceDependency>
        {
            new("IMyService", "_myService", "myService")
        };
        string result = RuleClassWriter.Render(CreateDefinition(dependencies: deps), null, null, null);
        result.Should().Contain("IMyService");
        result.Should().Contain("_myService");
    }

    [Fact]
    public void Render_WithDocComment_IncludesDocumentation()
    {
        string result = RuleClassWriter.Render(CreateDefinition(documentationComment: "Custom documentation"), null, null, null);
        result.Should().Contain("Custom documentation");
    }

    [Fact]
    public void Render_BoolReturnType_WrapsInRuleResult()
    {
        string result = RuleClassWriter.Render(CreateDefinition(returnType: "bool", isAsync: false), null, null, null);
        result.Should().Contain("RuleResult.Passed()");
        result.Should().Contain("RuleResult.Failure");
    }

    [Fact]
    public void Render_VoidReturnType_ReturnsTaskPassed()
    {
        string result = RuleClassWriter.Render(
            CreateDefinition(returnType: "void", isAsync: false, methodBody: "Console.WriteLine(\"test\");"),
            null, null, null);
        result.Should().Contain("RuleResult.Passed()");
    }

    [Fact]
    public void Render_IncludesUsings()
    {
        string result = RuleClassWriter.Render(CreateDefinition(), null, null, null);
        result.Should().Contain("using System.Linq;");
        result.Should().Contain("using Muonroi.RuleEngine.Abstractions;");
    }

    [Fact]
    public void ToIdentifier_ValidInput_ReturnsInput()
    {
        RuleClassWriter.ToIdentifier("ValidName").Should().Be("ValidName");
    }

    [Fact]
    public void ToIdentifier_Empty_ReturnsGeneratedRule()
    {
        RuleClassWriter.ToIdentifier("").Should().Be("GeneratedRule");
    }

    [Fact]
    public void ToIdentifier_StartsWithDigit_PrefixesWithR()
    {
        RuleClassWriter.ToIdentifier("1Rule").Should().Be("R_1Rule");
    }

    [Fact]
    public void ToIdentifier_SpecialChars_ReplacedWithUnderscore()
    {
        RuleClassWriter.ToIdentifier("my-rule.test").Should().Be("my_rule_test");
    }
}
