<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.RuleEngine.EntityFrameworkCore\Muonroi.RuleEngine.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.RuleEngine.Runtime\Muonroi.RuleEngine.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Tenancy.Core\Muonroi.Tenancy.Core.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Tenancy.Abstractions\Muonroi.Tenancy.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Governance.Abstractions\Muonroi.Governance.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.RuleEngine.Abstractions\Muonroi.RuleEngine.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Governance\Muonroi.Governance.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Core.Abstractions\Muonroi.Core.Abstractions.csproj" />
  </ItemGroup>

</Project>
