<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Muonroi.Governance.Abstractions" Version="1.0.0-alpha.1" />
    <PackageReference Include="Muonroi.RuleEngine.Abstractions" Version="1.0.0-alpha.1" />
    <PackageReference Include="Muonroi.RuleEngine.Core" Version="1.0.0-alpha.1" />
    <PackageReference Include="Muonroi.RuleEngine.Runtime" Version="1.0.0-alpha.1" />
  </ItemGroup>
</Project>
