<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.14" />
<PackageReference Include="Scriban" Version="7.0.3" />
<PackageReference Include="Serilog.Sinks.Elasticsearch" Version="9.0.3" />
</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.Messaging.MassTransit\Muonroi.Messaging.MassTransit.csproj" />
  </ItemGroup>
</Project>
