using Muonroi.RuleGen.Models;
using System.Text;

namespace Muonroi.RuleGen.Writers;

internal static class DispatcherWriter
{
    public static IReadOnlyList<DiscoveredDispatcherContext> BuildContexts(
        IReadOnlyCollection<DiscoveredRuleType> discovered,
        string dispatcherSuffix,
        string? workflowName = null)
    {
        if (string.IsNullOrWhiteSpace(dispatcherSuffix))
        {
            dispatcherSuffix = "RuleEngineDispatcher";
        }

        string[] contextTypes = [.. discovered
            .Select(x => x.ContextType)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)];

        Dictionary<string, int> stemCount = new(StringComparer.Ordinal);
        List<DiscoveredDispatcherContext> contexts = [];

        foreach (string contextType in contextTypes)
        {
            string stem = BuildDispatcherStem(contextType);
            if (stemCount.TryGetValue(stem, out int count))
            {
                count++;
                stemCount[stem] = count;
                stem = $"{stem}{count}";
            }
            else
            {
                stemCount[stem] = 1;
            }

            string className = $"{stem}{dispatcherSuffix}";
            string interfaceName = $"I{className}";
            contexts.Add(new DiscoveredDispatcherContext(
                contextType,
                interfaceName,
                className,
                $"{className}.g.cs",
                workflowName));
        }

        return contexts;
    }

    public static string Render(string outputNamespace, DiscoveredDispatcherContext context)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Muonroi.RuleEngine.Abstractions;");
        sb.AppendLine("using Muonroi.RuleEngine.Core;");

        bool versionAware = !string.IsNullOrWhiteSpace(context.WorkflowName);
        if (versionAware)
        {
            sb.AppendLine("using Muonroi.RuleEngine.Runtime.Rules;");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {outputNamespace};");
        sb.AppendLine();

        // Interface (unchanged)
        sb.AppendLine($"public interface {context.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    Task<FactBag> ExecuteAsync({context.ContextType} context, CancellationToken cancellationToken = default);");
        sb.AppendLine($"    Task<OrchestratorResult> ExecuteWithResultAsync(");
        sb.AppendLine($"        {context.ContextType} context,");
        sb.AppendLine("        ExecutionMode executionMode = ExecutionMode.AllOrNothing,");
        sb.AppendLine("        CancellationToken cancellationToken = default);");
        sb.AppendLine("}");
        sb.AppendLine();

        if (versionAware)
        {
            RenderVersionAwareDispatcher(sb, context);
        }
        else
        {
            RenderCodeFirstDispatcher(sb, context);
        }

        return sb.ToString();
    }

    private static void RenderCodeFirstDispatcher(StringBuilder sb, DiscoveredDispatcherContext context)
    {
        sb.AppendLine($"public class {context.ClassName}(RuleOrchestrator<{context.ContextType}> orchestrator) : {context.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public virtual Task<FactBag> ExecuteAsync(");
        sb.AppendLine($"        {context.ContextType} context,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return orchestrator.ExecuteAsync(context, cancellationToken: cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public virtual Task<OrchestratorResult> ExecuteWithResultAsync(");
        sb.AppendLine($"        {context.ContextType} context,");
        sb.AppendLine("        ExecutionMode executionMode = ExecutionMode.AllOrNothing,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return orchestrator.ExecuteWithResultAsync(");
        sb.AppendLine("            context,");
        sb.AppendLine("            executionMode,");
        sb.AppendLine("            cancellationToken: cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void RenderVersionAwareDispatcher(StringBuilder sb, DiscoveredDispatcherContext context)
    {
        sb.AppendLine($"public class {context.ClassName}(");
        sb.AppendLine($"    RuleOrchestrator<{context.ContextType}> orchestrator,");
        sb.AppendLine($"    RulesEngineService? rulesEngineService = null) : {context.InterfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private const string MWorkflowName = \"{context.WorkflowName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public virtual async Task<FactBag> ExecuteAsync(");
        sb.AppendLine($"        {context.ContextType} context,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (rulesEngineService is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            OrchestratorResult result = await rulesEngineService");
        sb.AppendLine("                .ExecuteWithResultAsync(MWorkflowName, context, cancellationToken);");
        sb.AppendLine("            return result.Facts;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return await orchestrator.ExecuteAsync(context, cancellationToken: cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public virtual async Task<OrchestratorResult> ExecuteWithResultAsync(");
        sb.AppendLine($"        {context.ContextType} context,");
        sb.AppendLine("        ExecutionMode executionMode = ExecutionMode.AllOrNothing,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (rulesEngineService is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            return await rulesEngineService");
        sb.AppendLine("                .ExecuteWithResultAsync(MWorkflowName, context, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return await orchestrator.ExecuteWithResultAsync(");
        sb.AppendLine("            context,");
        sb.AppendLine("            executionMode,");
        sb.AppendLine("            cancellationToken: cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string BuildDispatcherStem(string contextType)
    {
        string simpleType = ExtractSimpleTypeName(contextType);
        string normalized = RuleClassWriter.ToIdentifier(simpleType);
        if (string.IsNullOrWhiteSpace(normalized))
        {
            normalized = "Generated";
        }

        return normalized.EndsWith("Context", StringComparison.Ordinal)
            ? normalized[..^"Context".Length]
            : normalized;
    }

    private static string ExtractSimpleTypeName(string contextType)
    {
        string input = contextType.Trim();
        if (input.EndsWith("?", StringComparison.Ordinal))
        {
            input = input[..^1];
        }

        if (input.StartsWith("global::", StringComparison.Ordinal))
        {
            input = input["global::".Length..];
        }

        int genericStart = input.IndexOf('<');
        if (genericStart >= 0)
        {
            input = input[..genericStart];
        }

        int lastTypeToken = Math.Max(input.LastIndexOf('.'), input.LastIndexOf('+'));
        if (lastTypeToken >= 0 && lastTypeToken + 1 < input.Length)
        {
            input = input[(lastTypeToken + 1)..];
        }

        return input;
    }
}
