using Muonroi.RuleGen.Models;
using System.Text;

namespace Muonroi.RuleGen.Writers;

internal static class RegistrationWriter
{
    public static string Render(
        string outputNamespace,
        IReadOnlyCollection<DiscoveredRuleType> discovered,
        IReadOnlyCollection<DiscoveredDispatcherContext> dispatchers,
        bool includeRuleEngineRegistration,
        string registrationClassName)
    {
        string safeRegistrationClassName = NormalizeTypeName(registrationClassName);
        string[] ruleEngineLines = includeRuleEngineRegistration
            ? [.. discovered
                .Select(x => x.ContextType)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(x => x, StringComparer.Ordinal)
                .Select(x => $"        services.AddRuleEngine<{x}>();")]
            : [];

        string[] ruleLines = [.. discovered
            .OrderBy(x => x.ContextType, StringComparer.Ordinal)
            .ThenBy(x => x.ClassName, StringComparer.Ordinal)
            .Select(x => $"        services.TryAddEnumerable(ServiceDescriptor.Scoped(typeof(IRule<{x.ContextType}>), typeof({x.ClassName})));")];

        string[] dispatcherLines = [.. dispatchers
            .OrderBy(x => x.ContextType, StringComparer.Ordinal)
            .ThenBy(x => x.ClassName, StringComparer.Ordinal)
            .Select(x => $"        services.TryAddScoped<{x.InterfaceName}, {x.ClassName}>();")];

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Muonroi.RuleEngine.Abstractions;");
        if (includeRuleEngineRegistration)
        {
            sb.AppendLine("using Muonroi.RuleEngine.Core;");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {outputNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {safeRegistrationClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddMGeneratedRules(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (string? line in ruleEngineLines)
        {
            sb.AppendLine(line);
        }

        if (ruleEngineLines.Length > 0 && (ruleLines.Length > 0 || dispatcherLines.Length > 0))
        {
            sb.AppendLine();
        }

        foreach (string? line in ruleLines)
        {
            sb.AppendLine(line);
        }

        if (ruleLines.Length > 0 && dispatcherLines.Length > 0)
        {
            sb.AppendLine();
        }

        foreach (string? line in dispatcherLines)
        {
            sb.AppendLine(line);
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string NormalizeTypeName(string? raw)
    {
        string value = (raw ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(value))
        {
            return "MGeneratedRuleRegistrationExtensions";
        }

        if (char.IsDigit(value[0]))
        {
            value = "_" + value;
        }

        char[] buffer = value.ToCharArray();
        for (int i = 0; i < buffer.Length; i++)
        {
            if (!char.IsLetterOrDigit(buffer[i]) && buffer[i] != '_')
            {
                buffer[i] = '_';
            }
        }

        return new string(buffer);
    }
}
