using Muonroi.RuleGen.Models;
using System.Text;

namespace Muonroi.RuleGen.Writers;

internal static class RuleClassWriter
{
    public static string Render(
        ExtractedRuleDefinition definition,
        string? tenantId,
        string? author,
        string? gitCommit)
    {
        string className = $"{ToIdentifier(definition.Code)}Rule";
        (string dependencyFields, string dependencyCtor) = RenderDependencyConstructor(className, definition.Dependencies);
        string dependsOn = definition.DependsOn.Count == 0
            ? "Array.Empty<string>()"
            : $"new[] {{ {string.Join(", ", definition.DependsOn.Select(v => $"\"{Escape(v)}\""))} }}";

        string[] localFunction = RenderLocalFunction(definition);
        string[] helperMethods = RenderHelperMethods(definition.HelperMethods);
        string[] invokeLogic = RenderInvokeLogic(definition);
        bool evaluateNeedsAsync = invokeLogic.Any(line =>
            line.Contains("await ", StringComparison.Ordinal));

        HashSet<string> usings = new(StringComparer.Ordinal)
        {
            "using System;",
            "using System.Collections.Generic;",
            "using System.Threading;",
            "using System.Threading.Tasks;",
            "using Muonroi.RuleEngine.Abstractions;"
        };

        foreach (string u in definition.Usings)
        {
            string normalized = NormalizeUsingDirective(u);
            if (!string.IsNullOrWhiteSpace(normalized) &&
                !normalized.Equals("using Muonroi.RuleEngine.Abstractions;", StringComparison.Ordinal))
            {
                usings.Add(normalized);
            }
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"// GeneratedAtUtc: {DateTime.UtcNow:O}");
        if (!string.IsNullOrWhiteSpace(author))
        {
            sb.AppendLine($"// Author: {author}");
        }

        if (!string.IsNullOrWhiteSpace(gitCommit))
        {
            sb.AppendLine($"// Commit: {gitCommit}");
        }

        if (!string.IsNullOrWhiteSpace(tenantId))
        {
            sb.AppendLine($"// Tenant: {tenantId}");
        }

        sb.AppendLine("#nullable enable");

        foreach (string? u in usings.OrderBy(x => x, StringComparer.Ordinal))
        {
            sb.AppendLine(NormalizeUsingDirective(u));
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {definition.OutputNamespace};");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(definition.DocumentationComment))
        {
            // Ensure XML doc comments have /// prefix on each line
            foreach (string docLine in definition.DocumentationComment
                .Split(["\r\n", "\n"], StringSplitOptions.None))
            {
                string trimmed = docLine.TrimStart();
                if (trimmed.StartsWith("<", StringComparison.Ordinal) ||
                    trimmed.StartsWith("///", StringComparison.Ordinal) ||
                    string.IsNullOrWhiteSpace(trimmed))
                {
                    sb.AppendLine(trimmed.StartsWith("///", StringComparison.Ordinal)
                        ? docLine
                        : $"/// {trimmed}");
                }
                else
                {
                    sb.AppendLine($"/// {trimmed}");
                }
            }
        }
        else
        {
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Generated from {Path.GetFileName(definition.SourceFile)}:{definition.SourceLine} ({definition.ClassName}.{definition.MethodName}).");
            sb.AppendLine("/// </summary>");
        }

        sb.AppendLine($"public sealed class {className} : IRule<{definition.ContextType}>");
        sb.AppendLine("{");

        if (!string.IsNullOrWhiteSpace(dependencyFields))
        {
            sb.AppendLine(dependencyFields);
            sb.AppendLine();
            sb.AppendLine(dependencyCtor);
            sb.AppendLine();
        }

        sb.AppendLine($"    public string Code => \"{Escape(definition.Code)}\";");
        sb.AppendLine($"    public int Order => {definition.Order};");
        sb.AppendLine($"    public IReadOnlyList<string> DependsOn => {dependsOn};");
        sb.AppendLine($"    public Muonroi.RuleEngine.Abstractions.HookPoint HookPoint => Muonroi.RuleEngine.Abstractions.HookPoint.{definition.HookPoint};");
        sb.AppendLine("    public RuleType Type => RuleType.Validation;");
        sb.AppendLine($"    public string Name => \"{Escape(className)}\";");
        sb.AppendLine("    public IEnumerable<System.Type> Dependencies => Array.Empty<System.Type>();");
        sb.AppendLine();

        foreach (string attr in definition.CustomAttributes)
        {
            sb.AppendLine($"    {attr}");
        }

        string evaluateAsyncModifier = evaluateNeedsAsync ? "async " : string.Empty;
        sb.AppendLine($"    public {evaluateAsyncModifier}Task<RuleResult> EvaluateAsync({definition.ContextType} ctx, FactBag facts, CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");

        foreach (string line in localFunction)
        {
            sb.AppendLine($"            {line}");
        }

        sb.AppendLine();
        foreach (string line in invokeLogic)
        {
            sb.AppendLine($"            {line}");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        if (evaluateNeedsAsync)
        {
            sb.AppendLine("            return RuleResult.Failure(ex.Message);");
        }
        else
        {
            sb.AppendLine("            return Task.FromResult(RuleResult.Failure(ex.Message));");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public Task ExecuteAsync({definition.ContextType} context, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Task.CompletedTask;");
        sb.AppendLine("    }");

        foreach (string line in helperMethods)
        {
            sb.AppendLine(line);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string[] RenderHelperMethods(IReadOnlyList<HelperMethodDefinition> helpers)
    {
        if (helpers.Count == 0) return [];
        List<string> lines = [];

        foreach (HelperMethodDefinition helper in helpers)
        {
            lines.Add(string.Empty);
            string asyncModifier = helper.IsAsync ? "async " : string.Empty;
            string staticModifier = helper.IsStatic ? "static " : string.Empty;
            string parameters = string.Join(", ", helper.Parameters.Select(RenderParameter));
            lines.Add($"    private {staticModifier}{asyncModifier}{helper.ReturnType} {helper.MethodName}({parameters})");
            lines.Add("    {");

            if (!string.IsNullOrWhiteSpace(helper.MethodBody))
            {
                string[] bodyLines = ExtractBodyLines(helper.MethodBody);
                foreach (string? line in bodyLines)
                {
                    lines.Add($"        {line}");
                }
            }
            else if (!string.IsNullOrWhiteSpace(helper.ExpressionBody))
            {
                lines.Add($"        return {helper.ExpressionBody};");
            }
            else
            {
                lines.Add("        return default!;");
            }
            lines.Add("    }");
        }

        return [.. lines];
    }

    private static (string Fields, string Constructor) RenderDependencyConstructor(string className, IReadOnlyList<ServiceDependency> dependencies)
    {
        if (dependencies.Count == 0)
        {
            return (string.Empty, string.Empty);
        }

        string fields = string.Join(Environment.NewLine,
            dependencies.Select(d => $"    private readonly {d.TypeName} {d.FieldName};"));

        HashSet<string> usedParams = new(StringComparer.Ordinal);
        List<(ServiceDependency Dependency, string ParamName)> resolvedDeps = [];
        foreach (ServiceDependency dependency in dependencies)
        {
            string baseParam = string.IsNullOrWhiteSpace(dependency.ConstructorParameterName)
                ? ToCamelCase(dependency.FieldName.TrimStart('_'))
                : dependency.ConstructorParameterName;
            if (string.Equals(baseParam, dependency.FieldName, StringComparison.Ordinal))
            {
                string trimmed = baseParam.TrimStart('_');
                baseParam = string.IsNullOrWhiteSpace(trimmed)
                    ? "pValue"
                    : $"p{char.ToUpperInvariant(trimmed[0])}{trimmed[1..]}";
            }

            string candidate = baseParam;
            int suffix = 2;
            while (!usedParams.Add(candidate))
            {
                candidate = $"{baseParam}{suffix}";
                suffix++;
            }

            resolvedDeps.Add((dependency, candidate));
        }

        string args = string.Join(", ", resolvedDeps.Select(d => $"{d.Dependency.TypeName} {d.ParamName}"));
        string assigns = string.Join(Environment.NewLine,
            resolvedDeps.Select(d => $"        this.{d.Dependency.FieldName} = {d.ParamName};"));

        string ctor = $$"""
    public {{className}}({{args}})
    {
{{assigns}}
    }
""";

        return (fields, ctor);
    }

    private static string[] RenderLocalFunction(ExtractedRuleDefinition definition)
    {
        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string parameterList = string.Join(", ", definition.Parameters.Select(RenderParameter));
        string asyncModifier = NeedsAsyncLocalFunction(definition) ? "async " : string.Empty;
        string returnType = definition.ReturnType;

        List<string> lines =
        [
            $"{asyncModifier}{returnType} {localName}({parameterList})",
            "{"
        ];

        if (!string.IsNullOrWhiteSpace(definition.MethodBody))
        {
            string[] bodyLines = ExtractBodyLines(definition.MethodBody);
            foreach (string? line in bodyLines)
            {
                lines.Add($"    {line}");
            }
        }
        else if (!string.IsNullOrWhiteSpace(definition.ExpressionBody))
        {
            lines.Add($"    return {definition.ExpressionBody};");
        }
        else
        {
            lines.Add("    return default!;");
        }

        lines.Add("}");
        return [.. lines];
    }

    private static string[] ExtractBodyLines(string methodBody)
    {
        string body = methodBody.Trim();
        if (body.StartsWith("{", StringComparison.Ordinal) && body.EndsWith("}", StringComparison.Ordinal) && body.Length >= 2)
        {
            body = body[1..^1];
        }

        return [.. body
            .Split(["\r\n", "\n"], StringSplitOptions.None)
            .Select(x => x.TrimEnd())];
    }

    private static string[] RenderInvokeLogic(ExtractedRuleDefinition definition)
    {
        string localName = $"__source_{ToIdentifier(definition.MethodName)}";
        string args = string.Join(", ", definition.Parameters.Select(p => MapInvocationArgument(p, definition.ContextType)));
        string returnType = Normalize(definition.ReturnType);

        if (returnType == "Task<RuleResult>")
        {
            return
            [
                $"var __result = await {localName}({args});",
                "return __result;"
            ];
        }

        if (returnType == "RuleResult")
        {
            return
            [
                $"var __result = {localName}({args});",
                "return Task.FromResult(__result);"
            ];
        }

        if (returnType == "Task<bool>")
        {
            return
            [
                $"var __ok = await {localName}({args});",
                "return __ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\");"
            ];
        }

        if (returnType == "bool")
        {
            return
            [
                $"var __ok = {localName}({args});",
                "return Task.FromResult(__ok ? RuleResult.Passed() : RuleResult.Failure(\"Condition not met.\"));"
            ];
        }

        if (returnType == "Task")
        {
            return
            [
                $"await {localName}({args});",
                "return RuleResult.Passed();"
            ];
        }

        if (returnType == "void")
        {
            return
            [
                $"{localName}({args});",
                "return Task.FromResult(RuleResult.Passed());"
            ];
        }

        if (returnType.StartsWith("Task<", StringComparison.Ordinal))
        {
            return
            [
                $"var __value = await {localName}({args});",
                $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
                "return RuleResult.Passed();"
            ];
        }

        return
        [
            $"var __value = {localName}({args});",
            $"facts[\"{Escape(definition.Code)}:result\"] = __value;",
            "return Task.FromResult(RuleResult.Passed());"
        ];
    }

    private static string MapInvocationArgument(ParameterModel parameter, string contextType)
    {
        if (IsFactBagType(parameter.TypeName))
        {
            return "facts";
        }

        if (IsCancellationTokenType(parameter.TypeName))
        {
            return "ct";
        }

        if (string.Equals(Normalize(parameter.TypeName), Normalize(contextType), StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "ctx", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(parameter.Name, "context", StringComparison.OrdinalIgnoreCase))
        {
            return "ctx";
        }

        if (parameter.HasDefaultValue && !string.IsNullOrWhiteSpace(parameter.DefaultValueExpression))
        {
            return parameter.DefaultValueExpression!;
        }

        return "default!";
    }

    private static bool NeedsAsyncLocalFunction(ExtractedRuleDefinition definition)
    {
        if (definition.IsAsync)
        {
            return true;
        }

        string returnType = Normalize(definition.ReturnType);
        return returnType.StartsWith("Task", StringComparison.Ordinal);
    }

    private static string RenderParameter(ParameterModel p)
    {
        if (p.HasDefaultValue && !string.IsNullOrWhiteSpace(p.DefaultValueExpression))
        {
            return $"{p.TypeName} {p.Name} = {p.DefaultValueExpression}";
        }

        return $"{p.TypeName} {p.Name}";
    }

    private static string Normalize(string typeName)
    {
        return typeName.Replace(" ", string.Empty, StringComparison.Ordinal);
    }

    private static bool IsFactBagType(string typeName)
    {
        string normalized = Normalize(typeName);
        return string.Equals(normalized, "FactBag", StringComparison.Ordinal) ||
               string.Equals(normalized, "Muonroi.RuleEngine.Abstractions.FactBag", StringComparison.Ordinal);
    }

    private static bool IsCancellationTokenType(string typeName)
    {
        string normalized = Normalize(typeName);
        return string.Equals(normalized, "CancellationToken", StringComparison.Ordinal) ||
               string.Equals(normalized, "System.Threading.CancellationToken", StringComparison.Ordinal);
    }

    private static string NormalizeUsingDirective(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return string.Empty;
        }

        string normalized = value.Trim();
        if (!normalized.StartsWith("using ", StringComparison.Ordinal))
        {
            normalized = $"using {normalized}";
        }

        if (!normalized.EndsWith(";", StringComparison.Ordinal))
        {
            normalized += ";";
        }

        return normalized;
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        if (value.Length == 1)
        {
            return value.ToLowerInvariant();
        }

        return char.ToLowerInvariant(value[0]) + value[1..];
    }

    internal static string ToIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "GeneratedRule";
        }

        char[] chars = [.. value.Select(ch => char.IsLetterOrDigit(ch) || ch == '_' ? ch : '_')];
        string normalized = new(chars);

        if (!char.IsLetter(normalized[0]) && normalized[0] != '_')
        {
            normalized = $"R_{normalized}";
        }

        return normalized;
    }

    private static string Escape(string text)
    {
        return text.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}
