services:
  - name: local
    url: http://localhost:8181
bundles:
  authz:
    service: local
    resource: bundles/authz.tar.gz
    polling:
      min_delay_seconds: 60
      max_delay_seconds: 120