<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>Muonroi.Auth.Extended.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Fido2" />
    <PackageReference Include="Fido2.AspNet" />
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.Auth\Muonroi.Auth.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Core.Abstractions\Muonroi.Core.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Data.EntityFrameworkCore\Muonroi.Data.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Muonroi.Caching.Memory\Muonroi.Caching.Memory.csproj" />
  </ItemGroup>
</Project>