<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
<PackageReference Include="Scriban" Version="6.6.0" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Muonroi.AuthZ\Muonroi.AuthZ.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>


