param(
    [string]$Organization = "Muonroi Local Test",
    [string]$OutputDir = "$PSScriptRoot\generated-licenses",
    [string]$MasterKeyId = "mock-master-local",
    [int]$PaidValidDays = 365,
    [int]$EnterpriseValidDays = 365
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function New-RandomSegment {
    param([int]$Length = 4)

    $chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".ToCharArray()
    $builder = New-Object System.Text.StringBuilder

    for ($i = 0; $i -lt $Length; $i++) {
        $index = Get-Random -Minimum 0 -Maximum $chars.Length
        [void]$builder.Append($chars[$index])
    }

    return $builder.ToString()
}

function New-LicenseKey {
    param(
        [string]$Prefix,
        [string]$OrgName
    )

    $dateToken = [DateTimeOffset]::UtcNow.ToString("yyyyMMdd")
    return "$Prefix-$dateToken-$(New-RandomSegment)-$(New-RandomSegment)|$OrgName"
}

function New-ChildKeyRecord {
    param(
        [string]$Tier,
        [string]$OrgName,
        [int]$ValidDays,
        [string]$IssuedBy
    )

    $validWindow = if ($ValidDays -gt 0) { $ValidDays } else { 365 }
    $prefix = if ($Tier -eq "Enterprise") { "ENT" } else { "LIC" }
    $now = [DateTimeOffset]::UtcNow

    return [ordered]@{
        LicenseKey = New-LicenseKey -Prefix $prefix -OrgName $OrgName
        LicenseId = "lic_$([Guid]::NewGuid().ToString('N').Substring(0, 12))"
        OrganizationName = $OrgName
        Tier = $Tier
        IsActive = $true
        CreatedAtUtc = $now.ToString("O")
        ExpiresAtUtc = $now.AddDays($validWindow).ToString("O")
        IssuedBy = $IssuedBy
        Notes = "Generated by Generate-MockLicenseKeys.ps1"
        RevokedAtUtc = $null
        RevokedReason = $null
    }
}

if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$registryPath = Join-Path $OutputDir "license-registry.json"
$summaryPath = Join-Path $OutputDir "generated-license-keys.json"
$paidPath = Join-Path $OutputDir "paid-license.key"
$enterprisePath = Join-Path $OutputDir "enterprise-license.key"

$registry = $null
if (Test-Path $registryPath) {
    try {
        $registry = Get-Content -Path $registryPath -Raw | ConvertFrom-Json
    }
    catch {
        Write-Warning "Registry file exists but is invalid JSON. Recreating: $registryPath"
    }
}

if ($null -eq $registry) {
    $now = [DateTimeOffset]::UtcNow
    $registry = [ordered]@{
        MasterKeyId = $MasterKeyId
        CreatedAtUtc = $now.ToString("O")
        UpdatedAtUtc = $now.ToString("O")
        Keys = @()
    }
}
elseif (-not $registry.PSObject.Properties.Name.Contains("MasterKeyId") -or [string]::IsNullOrWhiteSpace($registry.MasterKeyId)) {
    $registry | Add-Member -MemberType NoteProperty -Name "MasterKeyId" -Value $MasterKeyId -Force
}

$paidRecord = New-ChildKeyRecord -Tier "Licensed" -OrgName $Organization -ValidDays $PaidValidDays -IssuedBy $registry.MasterKeyId
$enterpriseRecord = New-ChildKeyRecord -Tier "Enterprise" -OrgName $Organization -ValidDays $EnterpriseValidDays -IssuedBy $registry.MasterKeyId

$existing = @()
if ($registry.PSObject.Properties.Name.Contains("Keys") -and $null -ne $registry.Keys) {
    $existing = @($registry.Keys)
}

$registry.Keys = @($existing + $paidRecord + $enterpriseRecord)
$registry.UpdatedAtUtc = [DateTimeOffset]::UtcNow.ToString("O")

$registry | ConvertTo-Json -Depth 20 | Set-Content -Path $registryPath -Encoding UTF8
Set-Content -Path $paidPath -Value $paidRecord.LicenseKey -NoNewline -Encoding UTF8
Set-Content -Path $enterprisePath -Value $enterpriseRecord.LicenseKey -NoNewline -Encoding UTF8

$summary = [ordered]@{
    GeneratedAtUtc = [DateTimeOffset]::UtcNow.ToString("O")
    MasterKeyId = $registry.MasterKeyId
    Organization = $Organization
    PaidKey = $paidRecord.LicenseKey
    EnterpriseKey = $enterpriseRecord.LicenseKey
    RegistryPath = $registryPath
    TotalRegistryKeys = @($registry.Keys).Count
}

$summary | ConvertTo-Json -Depth 10 | Set-Content -Path $summaryPath -Encoding UTF8

Write-Host "Generated and registered child keys successfully:"
Write-Host "  Master Key Id:  $($registry.MasterKeyId)"
Write-Host "  Paid Key:       $($paidRecord.LicenseKey)"
Write-Host "  Enterprise Key: $($enterpriseRecord.LicenseKey)"
Write-Host "Saved files:"
Write-Host "  $paidPath"
Write-Host "  $enterprisePath"
Write-Host "  $summaryPath"
Write-Host "  $registryPath"
